### ISSUE TITLE
Nextcloud - php path configuration 

### ISSUE THREAD

**Issue by gpmeenen** [Wonderfall/dockerfiles#10]
Thanks for your nextcloud docker image.

After starting the container together with a mariadb container I get the following message on the admin panel:

> php does not seem to be setup properly to query system environment variables. The test with getenv("PATH") only returns an empty response.
> Please check the installation documentation for php configuration notes and the php configuration of your server, especially when using php-fpm. 

Have you encountered the same problem? Is there an easy way to fix it?

Greetings
Gerrit

**Comment by Wonderfall** [comment]
Actually there's nothing to worry about, I got the same problem.

I don't really know why this happens : 
https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/Dockerfile#L71
But I'm still investigating.

**Comment by Wonderfall** [comment]
It should be fixed now, please tell me if it's okay.

**Comment by gpmeenen** [comment]
Works fine - Thank you!
