### ISSUE TITLE
[NextCloud] Command "upgrade" is not defined.

### ISSUE THREAD

**Issue by s3131212** [Wonderfall/dockerfiles#101]
Hi, I tried this image recently and failed to setup NextCloud. The error message is:
```
Nextcloud is not installed - only a limited number of commands are available
[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "upgrade" is not defined.
Trying ownCloud upgrade again to work around ownCloud upgrade bug...
Nextcloud is not installed - only a limited number of commands are available
[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "upgrade" is not defined.
```
The docker-compose.yml is exactly the same as the example except I use mysql instead of mariadb.

Also, I've seen the following error message as well (but I don't know how to reproduce it, and I'm really sorry for that.)
```
Fatal Error Zend OPcache cannot allocate buffer for interned strings
```

Thanks a lot.

**Comment by Wonderfall** [comment]
For you first error this is most likely related to the database. Is the latter running without issue?

For opcache I think you can try to decrease (in opcache.ini) `opcache.interned_strings_buffer=16` to `8` for instance and tell me if the error message disappears.

**Comment by s3131212** [comment]
Thanks for replying.
After the first error appear, the container stop with exit code 1. Is there any way to solve the first error? Or do I need to import any SQL file before running the nextcloud container? I have tried to use the root user of MySQL but it didn't work as well.
I appreciate your help. :)


![image](https://cloud.githubusercontent.com/assets/4427280/22170373/a923cbb0-dfb7-11e6-8b18-989fc6cf4d7d.png)

docker-compose.yml
```
nginx:
  image: nginx
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/nginx/conf.d"
    - "/etc/nginx/vhost.d"
    - ./www:/usr/share/nginx/html:ro
    - ./certs:/etc/nginx/certs:ro
nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./template:/etc/docker-gen/templates:ro"
  volumes_from:
    - nginx
  entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-nginx-proxy-companion
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./certs:/etc/nginx/certs:rw
    - /etc/nginx/vhost.d
    - ./www:/usr/share/nginx/html:rw
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

#nextcloud
nextcloud:
  image: wonderfall/nextcloud
  #build: ./nc
  links:
    - mysql:mysql
  environment:
    - UID=1000
    - GID=1000
    - UPLOAD_MAX_SIZE=10G
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - REDIS_MAX_MEMORY=64mb
    - CRON_PERIOD=15m
    - TZ=Asia/Taipei
    - ADMIN_USER=admin
    - ADMIN_PASSWORD=admin
    - DB_TYPE=mysql
    - DB_NAME=nextcloud
    - DB_USER=nextcloud
    - DB_PASSWORD=password
    - DB_HOST=mysql
    # - VIRTUAL_HOST=
    # - LETSENCRYPT_HOST=
    # - LETSENCRYPT_EMAIL=s3131212@gmail.com
    # - VIRTUAL_PORT=8888
  volumes:
    - /mnt/nextcloud/data:/data
    - /mnt/nextcloud/config:/config
    - /mnt/nextcloud/apps:/apps2
# database
mysql:
  image: mysql:latest
  ports:
    # Allow client to access 3306
    - "3306:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
```

**Comment by Wonderfall** [comment]
How did you set up mysql? Did you create a nextcloud database?
If you want to make things easier, you can do like my example by using environment variables : https://github.com/Wonderfall/dockerfiles/tree/master/nextcloud#docker-compose-file-v1. But if you created a nextcloud database in your mysql instance, it should work.

**Comment by s3131212** [comment]
I have found out what the problem is. Since I restarted the container without finishing the installation wizard when the first run, I have to remove the config.php file or the upgrade wizard, which haven't set up, will be called and the error will appear.
Simply run `rm /mnt/nextcloud/config/config.php` and everything will be fine.

**Comment by lojasmarques** [comment]
Não é possivel excluir 
-bash-4.1$ rm /mnt/nextcloud/config/config.php
rm: cannot remove `/mnt/nextcloud/config/config.php': No such file or directory

e não consigo executar o comando Update no $ composer
