### ISSUE TITLE
[nextcloud] Build for ARM hangs on (2/160) Installing perl (5.24.1-r0)

### ISSUE THREAD

**Issue by alex6480** [Wonderfall/dockerfiles#104]
I've tried building this for ARM on a raspberry PI 2 with the instructions from docker hub, and it hangs on this line.

> (2/160) Installing perl (5.24.1-r0)

I've waited ~30 minutes now and nothing has happened.

**Comment by Wonderfall** [comment]
Can you try again later (maybe at the time you see this)? 
It sometimes happens while using Alpine Linux.

**Comment by alex6480** [comment]
I tried again today and it hung up at the exact same place. If I create a new docker container from the base image and try to install perl manually it gets to around 80% in a few seconds and then stops progressing.

So it's probably not a problem with your image, but I would still like some help on how to solve it.
