### ISSUE TITLE
[nextcloud] Random "Request Entity Too Large"

### ISSUE THREAD

**Issue by Holt59** [Wonderfall/dockerfiles#106]
Hi,

Thanks for the image.

I installed the nextcloud container behind a nginx proxy, and set `client_max_body_size 10g;` on the proxy configuration. 

However, I still get some random "Request Entity Too Large", even though there are no logs on my nginx proxy (before setting the `client_max_body_size`, I had logs about these on my servers).

The `client_max_body_size` seems to working properly since I have 500MB file on the server, but some random files are stuck on my computer. I try to see if there were some common attributes for these files, but this seems kind of random... : 

- `.mp3` files (some with sizes smaller than `.mp3` files that were uploaded correctly);
- `.dvix` files with large size (~600 MB);
- "large" `.pdf` (~35MB);
- Some `.jpg` files...

All the files I am trying to sync are from a previous owncloud installation (I copy-pasted the content of my old folder to a new folder), I don't know if it may cause the issue...

**Comment by jkaberg** [comment]
I'm also seeing the very same behaviour, did you find an solution @Holt59 ?

**Comment by Holt59** [comment]
@jkaberg I did a complete reinstallation of the **nextcloud client** and it worked, so I think it is not related to this image actually... I think there is some synchronization issue with the nextcloud client when you modify the server configuration while the client is up and running.

**Comment by jkaberg** [comment]
@Holt59 Ah, alright. 

Found my error; adding `client_max_body_size 10G;` to the server part of my reverse (nginx) proxy (which sits infront of the docker container) solved it 😄

**Comment by Wonderfall** [comment]
Glad it's fixed, feel free to reopen if needed.
