### ISSUE TITLE
[searx] SSL Packages not picked up

### ISSUE THREAD

**Issue by Excape** [Wonderfall/dockerfiles#110]
When I start a searx instance, the following message appears:
```
CRITICAL:searx.webapp:The pyopenssl, ndg-httpsclient, pyasn1 packages have to be installed.
Some HTTPS connections will fail
```
And probably because of this, requests to the google engine fail

```
ERROR:searx.search:engine google : requests exception(search duration : 0.106167793274 s, timeout: 2.0 s) : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```

Note: I run searx through a reverse-proxy with nginx-proxy and TLS, but the error comes from the searx container, so I don't think that has any influence.

When I connect to a shell in the running container, the packages seem to be installed:
```
/ # pip list
Babel (2.3.4)
certifi (2016.9.26)
cffi (1.9.1)
click (6.7)
cryptography (1.7.1)
enum34 (1.1.6)
Flask (0.12)
Flask-Babel (0.11.1)
idna (2.2)
ipaddress (1.0.18)
itsdangerous (0.24)
Jinja2 (2.9.4)
lxml (3.7.1)
MarkupSafe (0.23)
ndg-httpsclient (0.4.2)
pip (9.0.1)
pyasn1 (0.1.9)
pycparser (2.17)
Pygments (2.1.3)
pyOpenSSL (16.2.0)
PySocks (1.6.5)
python-dateutil (2.5.3)
pytz (2016.10)
PyYAML (3.11)
requests (2.12.4)
setuptools (33.1.1.post20170119)
six (1.10.0)
Werkzeug (0.11.15)
```

**Comment by Wonderfall** [comment]
I know and I've already checked if theses packages were installed.
I'm afraid I don't know more than you...

**Comment by tognellap** [comment]
I have the same issue on my side

**Comment by jon1012** [comment]
Yup same here... tried to update everything and recreate containers with no luck :(
