### ISSUE TITLE
[nextcloud] not honoring environment

### ISSUE THREAD

**Issue by bobberb** [Wonderfall/dockerfiles#113]
After executing the following:
```

docker run --name nextcloud \
       -v /tank/selfhosted/nextcloud/data:/data \
       -v /tank/selfhosted/nextcloud/config:/config \
       -v /tank/selfhosted/nextcloud/apps:/apps2 \
       -e UID=1000 -e GID=1000 \
       -e UPLOAD_MAX_SIZE=10G \
       -e APC_SHM_SIZE=128M \
       -e OPCACHE_MEM_SIZE=128 \
       -e REDIS_MAX_MEMORY=64mb \
       -e CRON_PERIOD=15m \
       -e TZ=Etc/UTC \
       -e ADMIN_USER=admin \
       -e ADMIN_PASSWORD=admin \
       -e DB_TYPE=mysql \
       -e DB_NAME=nextcloud \
       -e DB_USER=nextcloud \
       -e DB_PASSWORD=nextcloud \
       -e DB_HOST=172.17.0.1 \
       wonderfall/nextcloud:latest
```

The following error is thrown, I do not know where "oc_admin" comes from or what the image expects the password to be.

```
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occ
ured in driver: SQLSTATE[28000] [1045] Access denied for user 'oc_admin'@'172.17
.0.4' (using password: YES) in /nextcloud/lib/private/DB/Connection.php:60
```

**Comment by Wonderfall** [comment]
Did you link a MySQL container? Or is there a server running at 172.17.0.1 with the databse created, etc.?

**Comment by bobberb** [comment]
There is one running on 172.17.0.1. 

But that doesn't explain where "oc_admin" came from :( .

**Comment by tbrasser** [comment]
oc_ is the default database table prefix. So quite strange that it gets put in front of the user as well...

The automatic database creation has never worked for me. I've always had to attach to my MariaDB container, manually add the user and database, grant all privileges and then it would work.

**Comment by bobberb** [comment]
@tbrasser I will attempt a boot of this image with a premade oc_admin user. Have you noted the environment MYSQL_ROOT_PASSWORD not being honored or will this just be a simple username swap?

**Comment by bobberb** [comment]
@Wonderfall @tbrasser 
I made an oc_admin user but I still get the error 

```
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occ
ured in driver: SQLSTATE[28000] [1045] Access denied for user 'oc_admin'@'172.17
.0.4' (using password: YES) in /nextcloud/lib/private/DB/Connection.php:60
```

I assume there is some sort of password I am not privy to. I used to use this image, what has happened?

**Comment by bobberb** [comment]
Foolish me, I was keeping an old config.php.
