### ISSUE TITLE
Cannot Install Custom App in NectCloud

### ISSUE THREAD

**Issue by schrieveslaach** [Wonderfall/dockerfiles#117]
I'm developing a [custom app](https://gitlab.com/schrieveslaach/nextcloud-spgverein-app) for nextcloud which is not yet published. 

I copied the content of the repository into a sub directory of the local `/apps` directory, restarted NextCloud container, but the app did not show up. 

Any ideas?

**Comment by Wonderfall** [comment]
You should install your app in \apps2 (root), this should work.
https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/11.0/setup.sh#L17-L28

**Comment by schrieveslaach** [comment]
Sorry, there was a typo... I'm running the container by following command

```
/usr/bin/docker run -d \
		-v /srv/owncloud-data/:/data \
		-v /srv/nextcloud-apps/:/apps2 \
		-v /srv/nextcloud-config/:/config \
		-p 127.0.0.1:8888:8888  \
		--name nextcloud \
		wonderfall/nextcloud:11.0
```

Then, I copy my custom app into `/srv/nextcloud-apps/`. However, the app does not show up...

**Comment by Wonderfall** [comment]
Ok so you're doing well. Did you try on another image/instance?
