### ISSUE TITLE
[nginx] bad gateway on some requests

### ISSUE THREAD

**Issue by MaStr** [Wonderfall/dockerfiles#120]
Hi,
Thank you for providing the image.

I am running your image on my QNAP together with a mariadb container. The 8888 port is forwarded by a NAT configuration <nasip>:18888 -> docker container 8888

I am running into an issue with the nginx configuration, because some HTTP requests are returned with "502 bad gateway". This causes issues in the configuration-menu.. for example I am not able to configure additional apps. In the same time, the normal features like, file up- and download, are working.

Requests like this are:
http://<ip>:18888/settings/apps/list?category=disabled
Respones:  "502 bad gateway"

I checked var/log/nginx/error.log  - empty :-( 
Also no error entries inside the php-fpm log.

Same is true for: http://192.168.56.105:18888/settings/ajax/checksetup

In the docker container console I can see messages like this

````
[16-Feb-2017 12:29:40] WARNING: [pool www] child 248 exited on signal 9 (SIGKILL) after 797.271879 seconds from start                     
[16-Feb-2017 12:30:57] WARNING: [pool www] child 250 exited on signal 9 (SIGKILL) after 862.642624 seconds from start                     
[16-Feb-2017 12:30:57] NOTICE: [pool www] child 262 started                                                                               
[16-Feb-2017 12:30:57] WARNING: [pool www] child 260 exited on signal 9 (SIGKILL) after 73.832626 seconds from start                      
[16-Feb-2017 12:30:57] NOTICE: [pool www] child 263 started 
````
It seems related, because other page-loads do not cause such messages.

I increased the nextcloud-log to level 1 and to a file, but I can only see messages like this

````
{"reqId":"k+d21XHew5xCYtPpKwQk","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","level":1,"time":"2017-02-16 12:24:07","method":"--","url":"--","user":"--","version":"11.0.1.2"}
````
This looks unrelated for my eyes.

I need some advice for valuable debugging commands on nginx or things I should provide to get closer to the problem. What could be possible wrong?

Thank you,
Best regards
Matthias

**Comment by MaStr** [comment]
I did further researches today. It seems to be less likely a nginx issue, but something in the area php-fpm or docker environment. 
Still researching..

**Comment by MaStr** [comment]
Ok, I found out that is a QNAP related issue. I will file a ticket against QNAP.
Amazing... not. Took me 2,5 days working on this. 

Thank you for that container, it works on my debian like a charm!

**Comment by imacks** [comment]
@MaStr hey there i am running into the same issue on a rancher setup. can you tell me more about your QNAP issue? I suspect it may not be an isolated incident

**Comment by MaStr** [comment]
Not much more. Because the container and the operating system does not talk much about failing syscalls (or other things), there were literatly NO indication what is wrong. Only moving the container to a newer level of Docker and OperatingSystem (in a VM) simply wiped that issue away.
If you have access to kernel logs etc, try to get something like an strace from the running container, that might help... or not ;-)
