### ISSUE TITLE
PHP-Redis missed - Scale not possible

### ISSUE THREAD

**Issue by Berndinox** [Wonderfall/dockerfiles#121]
Cause PHP-Redis is missing it is not possible to point to an ditributed redis instance.
Cause of this, you are bind to local caching methods, that results in beeing not able to scale nextcloud on an docker swarm.

So, please add php-redis.

> As i can see php7.1redis is not available jet, may manuel install is necessarry?

BR

**Comment by Wonderfall** [comment]
I would like to, and I know php7.1-redis is not available yet. But even when using pecl, the module is built and installed, yet php is saying the module "cannot be recognised". I find nothing about this...

If you want to help, you can try to make it work. I'm very busy and I've spent enough time looking around for a solution. So I ended up removing the extension ; not very professional I know, but I've made this image and  I maintain it for my own use first. However I don't say I'm not open to suggestions, and you can be sure I will add php-redis extension again (or merge a pull request)... if it works.

**Comment by Berndinox** [comment]
@Wonderfall  i'll try... stay tuned
