### ISSUE TITLE
[Howto?] start occ files:scan

### ISSUE THREAD

**Issue by Berndinox** [Wonderfall/dockerfiles#125]
I would like to start a file scan, however its not possible cause sudo or su do not work..
Please help me out :)

**Comment by Wonderfall** [comment]
`docker exec -ti nextcloud occ files:scan`
There's an `occ` script I've made using `su-exec` so it's even easier to use.

**Comment by skriems** [comment]
Just for reference, because I learned about Wonderfall's script just now:

```
$ apk add sudo
$ sudo -u \#991 php7 path/to/occ files:scan
```

**Comment by Berndinox** [comment]
Nice, thanks!

Von meinem iPhone gesendet
