### ISSUE TITLE
[boring-nginx] autoindex

### ISSUE THREAD

**Issue by saeroshi** [Wonderfall/dockerfiles#126]
Bonsoir,

Je souhaiterais savoir pouvoir le module ngx_http_autoindex_module est actuellement enlevé de la compilation ?

Cordialement,
Saeroshi

**Comment by Wonderfall** [comment]
My images were made for my own use, so as I don't need this module I don't want to have it compiled with nginx (basic tips for hardening security).

If you want to have it enabled you're 100% free to clone and remove the line. ;)

**Comment by saeroshi** [comment]
Oki,
thanks.

**Comment by frebib** [comment]
To fix this I just added another container using `nginx:alpine` for the particular vhost and added a proxy_pass entry to the upstream server. I realise it's not a particularly ideal solution but it's always an option
