### ISSUE TITLE
nginx dynamic tls records default by disabled?

### ISSUE THREAD

**Issue by denji** [Wonderfall/dockerfiles#129]
https://github.com/cujanovic/nginx-dynamic-tls-records-patch/blob/master/nginx__dynamic_tls_records_1.11.5%2B.patch#L192

```nginx
http {
  ssl_dyn_rec_enable on;
}
```

**Comment by Wonderfall** [comment]
Indeed I think I prefer this to be enabled by default.

**Comment by denji** [comment]
> I prefer this to be enabled by default.
actually disabled :)

**Comment by Wonderfall** [comment]
Until I pushed bd3e5d9? My mistake. I completely forgot it would be better to do so if the user cannot easily access `nginx.conf` (I use a volume for mounting this single file as Docker allows it, but I'd like the default configuration to be "optimised" so a volume is not required).
