### ISSUE TITLE
[nextcloud] Can't download any files

### ISSUE THREAD

**Issue by kuche1991** [Wonderfall/dockerfiles#134]
After updating today i wasn't able to Download any files. Neither in the Webinterface, nor in the app.
Also the background image of the login-page doesn't load anymore (even after uploading a new one).

This is what I'm getting out of the nextcloud.log-file:

`
{"reqId":"SBQAynwuQo1RZb0caPDm","remoteAddr":"172.18.0.8","app":"PHP","message":"Redis::connect(): connect() failed: No such file or directory at \/nextcloud\/lib\/private\/RedisFactory.php#61","level":3,"time":"2017-02-25 01:39:25","method":"GET","url":"\/remote.php\/webdav\/Screenshot_1481220660.png","user":"test","version":"11.0.1.2"}
{"reqId":"SBQAynwuQo1RZb0caPDm","remoteAddr":"172.18.0.8","app":"webdav","message":"Exception: {\"Message\":\"Redis server went away\",\"Exception\":\"RedisException\",\"Code\":0,\"Trace\":\"#0 \\\/nextcloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php(114): Redis->incrBy('c803362cd3b66bf...', 1)\\n#1 \\\/nextcloud\\\/lib\\\/private\\\/Lock\\\/MemcacheLockingProvider.php(73): OC\\\\Memcache\\\\Redis->inc('files\\\/97d76eed5...')\\n#2 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\MemcacheLockingProvider->acquireLock('files\\\/97d76eed5...', 1)\\n#3 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/Screensho...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#4 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Screensho...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#5 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Screensho...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#6 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1997): OC\\\\Files\\\\View->lockPath('\\\/Screenshot_148...', 1, false)\\n#7 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1110): OC\\\\Files\\\\View->lockFile('\\\/Screenshot_148...', 1)\\n#8 \\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(967): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/Screenshot_148...', Array, 'rb')\\n#9 \\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(305): OC\\\\Files\\\\View->fopen('Screenshot_1481...', 'rb')\\n#10 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#11 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#14 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/nextcloud\\\/remote.php(165): require_once('\\\/nextcloud\\\/apps...')\\n#17 {main}\",\"File\":\"\\\/nextcloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php\",\"Line\":114,\"User\":\"test\"}","level":4,"time":"2017-02-25 01:39:25","method":"GET","url":"\/remote.php\/webdav\/Screenshot_1481220660.png","user":"test","version":"11.0.1.2"}
`

Anyone else got the same problem?

Any solutions?

**Comment by Wonderfall** [comment]
Redis server is not included anymore in the container (it shouldn't be), that's why you have this problem after the upgrade. The PHP redis extension is still provided, you can either remove redis configuration from config.php or use redis server in a container (this will require modification to config.php too, but it's very simple) : https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/README.md#how-to-configure-redis

Sorry for making changes like that, if I had a way to warn all users I would do that. :)

**Comment by kuche1991** [comment]
Thx very much, have set up a redis server and it's working like a charm again :+1:
