### ISSUE TITLE
[nextcloud] nginx 403 error pages break adding users with 'Password policy' enabled.

### ISSUE THREAD

**Issue by frebib** [Wonderfall/dockerfiles#137]
```
/etc/nginx/nginx.conf:40
-----------------------------------
error_page 403 /core/templates/403.php
```

The above line masks error responses returned by the nextcloud server preventing error message bars appearing on the 'add user' page [example error message](https://i.imgur.com/dAGIonE.png)

It can be very unclear as to what is happening like this as it is not obvious to the user what is happening; the user isn't added and there are no errors or warnings.

**Comment by InfernoZeus** [comment]
This was very confusing when first installing Nextcloud and not knowing that it has password restrictions.

@Wonderfall Looks like that configuration line has been removed from NextCloud's suggested nginx.conf [(link to merged pull)](https://github.com/nextcloud/documentation/pull/392). Are you open to a pull request to do the same?
