### ISSUE TITLE
[nextcloud] update@ hub.docker 

### ISSUE THREAD

**Issue by ghost** [Wonderfall/dockerfiles#138]
i'd like to get 11.0.2
can you pls update the build at 
https://hub.docker.com/r/wonderfall/nextcloud/

Thank you very much!

**Comment by Wonderfall** [comment]
I can't do that now.
https://bugs.alpinelinux.org/issues/6937

It'll fail like there : https://hub.docker.com/r/wonderfall/nextcloud/builds/bcezgzs2c6yctgmzpjxhh7y/
I can do a temporary fix but it would be better to wait for the maintainer to fix the issue. If it lasts too much I will do that fix.

**Comment by ghost** [comment]
Ah okay. Bummer!
Thank you anyway!

Am 27. Feb. 2017, 22:23 +0100 schrieb Wonderfall <notifications@github.com>:

**Comment by Wonderfall** [comment]
Now it should be good and it's currently building.

**Comment by ghost** [comment]
great. works perfect :)
