### ISSUE TITLE
Redirect output /dev/stdout & /dev/stderr

### ISSUE THREAD

**Issue by denji** [Wonderfall/dockerfiles#142]
* https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/Dockerfile#L126-L128
* https://docs.docker.com/engine/admin/logging/overview/

```Dockerfile
	# forward request and error logs to docker log collector
	&& ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
```

docker logs -f boring-nginx
docker-compose logs -f boring-nginx

**Comment by Wonderfall** [comment]
I couldn't get it working like this (I would like to but I don't know yet how).

**Comment by denji** [comment]
Little [cleaned-up fork with stdout & stderr](https://github.com/nginx-modules/docker-nginx-boringssl/blob/master/mainline/alpine/Dockerfile#L100-L173): but having problems reducing the size and build nginx-1.10.x
