### ISSUE TITLE
[nextcloud] Redis::connect(): connect() failed: No such file or directory at /nextcloud/lib/private/RedisFactory.php#61

### ISSUE THREAD

**Issue by yurivanmidden** [Wonderfall/dockerfiles#143]
After pulling the latest image, I get `Redis::connect(): connect() failed: No such file or directory at /nextcloud/lib/private/RedisFactory.php#61`. I am also unable to download any files from Nextcloud. 

The system is running Debian Wheezy (kernel 3.16)

> Containers: 8
>  Running: 7
>  Paused: 0
>  Stopped: 1
> Images: 281
> Server Version: 1.12.6
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 323
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge null host overlay
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Security Options:
> Kernel Version: 3.16.0-4-amd64
> Operating System: Debian GNU/Linux 8 (jessie)
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 7.766 GiB
> Name: harambee
> ID: NVCP:5M7Q:UN4F:FQCA:W4WY:NXCW:QSPC:SFNK:Y2HJ:LLCV:QRWV:F6CE
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> WARNING: No memory limit support
> WARNING: No swap limit support
> WARNING: No kernel memory limit support
> WARNING: No oom kill disable support
> WARNING: No cpu cfs quota support
> WARNING: No cpu cfs period support
> Insecure Registries:
>  127.0.0.0/8

**Comment by hensur** [comment]
I have the same issue with the latest image. When I try to download files I get an Internal Server Error. The nextcloud log is full of Redis connect() errors.
Edit: I just tried using the daily image, but the Redis error is still there.

**Comment by Wonderfall** [comment]
I'm sorry for the lack of communication but there was a lot of issues about it...
My answer to your problem here : https://github.com/Wonderfall/dockerfiles/issues/128#issuecomment-281509540
