### ISSUE TITLE
[nextcloud] Redis server went away

### ISSUE THREAD

**Issue by Nobody84** [Wonderfall/dockerfiles#144]
Hi,

if have upgraded my docker container to 11.0 and I'm not able to log into my nextcloud account. I searched the log and I found an exception which told me that the "Redis server went away". 
I'm not very into Redis and I did't get a clue whats going wrong.

Ich attached the log file because the output is to big to post it within the post. 
[nextcloud.log.txt](https://github.com/Wonderfall/dockerfiles/files/817541/nextcloud.log.txt)

I hope you can help me with this.

**Comment by Wonderfall** [comment]
https://github.com/Wonderfall/dockerfiles/issues/128#issuecomment-281509540 (hope it'll help)
I like helping but try to search a bit more next time (this is the fourth issue about it) :)
