### ISSUE TITLE
Nextcloud UID/GID

### ISSUE THREAD

**Issue by jatty** [Wonderfall/dockerfiles#145]
The docker-compose sample for nextcloud includes the options UID/GID environment variables:
`    - UID=1000`
`    - GID=1000`
(see https://hub.docker.com/r/wonderfall/nextcloud/)

but /etc/passwd and /etc/group don't get aligned for user nginx.
It should read
` /etc/passwd: nginx:x:1000:1000:nginx:/var/lib/nginx:/sbin/nologin`
`  /etc/group: nginx:x:1000:nginx`

**Comment by Wonderfall** [comment]
We don't use the user/group nginx, we launch nginx under these UID/GID.
You can check with `ps aux`.

https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/11.0/run.sh#L45
-> https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/11.0/s6.d/nginx/run

**Comment by jatty** [comment]
Yes, in fact.
This is a rather cosmetic issue only.
