### ISSUE TITLE
Redis Connect Failed

### ISSUE THREAD

**Issue by xcellardoor** [Wonderfall/dockerfiles#146]
Hi there,

Thanks for the all the hard work you go to in providing this image, but unfortunately I think I've found a bug. 

I did a Docker pull from 11.0.1 (I believe it was) to your Latest tag, and then when I re-span up the container with my previous volumes, I discovered I couldn't upload anything, create new files or folders and so on. If I go into the Logging page of Nextcloud it's being spammed with these messages.

Redis::connect(): connect() failed: No such file or directory at /nextcloud/lib/private/RedisFactory.php#61

That line appears to be a connection directive in the file, but I didn't opt to run Redis? The command I use to start the container is:

docker run -d --name nextcloud-service -p 127.0.0.1:50080:8888 -v nextcloud-data:/data -v nextcloud-config:/config -v nextcloud-apps:/apps2 -e UPLOAD_MAX_SIZE=20G wonderfall/nextcloud:latest

Many thanks in advance for your help,

**Comment by Wonderfall** [comment]
5th issue about it. :(
https://github.com/Wonderfall/dockerfiles/issues/128#issuecomment-281509540

**Comment by xcellardoor** [comment]
@Wonderfall Thanks for the reply! Sorry I didn't spot those other posts earlier.

I just spun up a Redis container quick and easy and put both Nextcloud and Redis in the same docker virtual network, then edited the config file of nextcloud to point to it. Things seem to be behaving now. Many thanks.

**Comment by Wonderfall** [comment]
You're welcome anyway. ;)
It's a better approach to use a separated Redis container, I think. But during some time config.php was automatically configured to add a redis configuration for a local server, which is not present anymore, hence the issues (and you won't be the last one).
