### ISSUE TITLE
Certificate Issues with Calendar

### ISSUE THREAD

**Issue by benyanke** [Wonderfall/dockerfiles#147]
See here, and the solution required:

https://github.com/nextcloud/calendar/issues/250

**Comment by Wonderfall** [comment]
Did https://github.com/Wonderfall/dockerfiles/commit/8f7a3f8f3bba4a04c21122d2a02b9bd7e1b12d76 fix your issue?

**Comment by dalareo** [comment]
I updated the image but still getting the same error:

```
Error al solicitar recurso al servidor remoto. Esto puede estar relacionado con un error de certificado
```

Translate: error trying to get remote server resource. This can be related to a certificate error

**Comment by benyanke** [comment]
Sorry I missed this, but it did resolve my issue.

Here's a private url for my debugging calendar for anyone else who might find the ability to test useful.

https://calendar.google.com/calendar/ical/benyanke.com_h845b7ivfu249ltaomhrhus178%40group.calendar.google.com/private-2b78935486dd72d024f5d01f25930a3f/basic.ics

**Comment by benyanke** [comment]
Sorry I missed this @Wonderfall, but it did resolve my issue. Thanks for being an awesome image for my NextCloud instance.

Here's a private url for my debugging calendar for anyone else who might find the ability to test useful.

[https://calendar.google.com/calendar/ical/benyanke.com_h845b7ivfu249ltaomhrhus178%40group.calendar.google.com/private-2b78935486dd72d024f5d01f25930a3f/basic.ics](https://calendar.google.com/calendar/ical/benyanke.com_h845b7ivfu249ltaomhrhus178%40group.calendar.google.com/private-2b78935486dd72d024f5d01f25930a3f/basic.ics)

@dalareo  - see if you can add the URL above as a calendar.

**Comment by dalareo** [comment]
Hi @benyanke I am not using Wonderfall image anymore. Sorry. Using nextcloud:fpm official image instead with a load balancer in front of.
