### ISSUE TITLE
Cannot install Mail app

### ISSUE THREAD

**Issue by frabe1579** [Wonderfall/dockerfiles#148]
From the App store, Mail cannot be installed because "PHP with a version lower than 7.0 is required". In another system I have a regular nextcloud host with PHP 7.0, with Mail app correctly installed and running.
Image: nextcloud:11.0, accessed with a reverse proxy. All is ok, apparently no other app has this problem.
Maybe the message is wrong, or Mail is incompatible with 7.1, or something other wrong?

**Comment by Wonderfall** [comment]
Mail is not compatible with PHP 7.1 It should be in the next release, it's not up to me. :(
