### ISSUE TITLE
Update through nextcloud

### ISSUE THREAD

**Issue by jaithn** [Wonderfall/dockerfiles#150]
Hey guys,
i am running your nextcloud docker and it is working perfectly. Thanks!!

If i try to update through the webinterface with admin account I get the following error:

> Check for expected files
> The following extra files have been found:
> apps2

Do you know what to do?

Thanks,
Jaithn

**Comment by Wonderfall** [comment]
Not really. But the preferred solution I think is to update the image and recreate the container (latest 11.0.2 provided). It'll also update other system package so it's better to do that sometimes. ;) 

I didn't try the update from the web interface, you mean you're using the updater app right ?

**Comment by lachmanfrantisek** [comment]
I think that problem is in `nextcloud` folder structure. Updater needs `/nextcloud/apps2` to be a directory, not a link.

**Comment by Wonderfall** [comment]
I'm closing this because the preferred way to update is to recreate the container.  It's the "Docker-way". It's also a good practice so you can upgrade system components occasionally.
