### ISSUE TITLE
[Nextcloud] PHP Module Iconv not installed.

### ISSUE THREAD

**Issue by tbrasser** [Wonderfall/dockerfiles#151]
After the previous php error, my nextcloud installation has been running fine. But now, since today, i got this: http://pastebin.com/Z8QzYS51

**Comment by Wonderfall** [comment]
https://github.com/Wonderfall/dockerfiles/commit/7e50fa836d5bb4d0309940617bca841e553b2775
php7.1 packages were updated tonight with the brillant idea to move the modules location.
