### ISSUE TITLE
[nextCloud]Logout fail

### ISSUE THREAD

**Issue by 89day** [Wonderfall/dockerfiles#152]
Logout link to http://127.0.0.1:8888/logout?requesttoken=........ but not my domain.How to fix it? thak you.

**Comment by Wonderfall** [comment]
Did you set the `$DOMAIN` environment variable before installing?
If you didn't do so you'll have ton configure manually `config.php` like a classic Nextcloud instance : https://docs.nextcloud.com/server/11/admin_manual/configuration_server/automatic_configuration.html
