### ISSUE TITLE
[nextcloud] Default encryption module couldn't be installed

### ISSUE THREAD

**Issue by PersonaA** [Wonderfall/dockerfiles#154]
Got fresh Nextcloud 11.0.2. Tried to activate Default encryption module and got this:
> Error: this app cannot be enabled because it makes the server unstable

**Comment by Wonderfall** [comment]
I tried a fresh install of the last build, I couldn't reproduce your problem.
More details ? How do you run the container ? Some interesting log entries ?

**Comment by PersonaA** [comment]
Now it works. I cannot really figure out what happened but now Default encryption module is enabled and working. I commented `'memcache.local'`, `'memcache.locking' => '\\OC\\Memcache\\Redis'` and `'redis'` in config.

My installation set with MariaDB without Redis.

**Comment by Wonderfall** [comment]
Is it the last build ? It shouldn't have this in config.php since I removed it by default
https://github.com/Wonderfall/dockerfiles/issues/128#issuecomment-281509540

**Comment by PersonaA** [comment]
Config file was generated in external directory in December when I made my first attempt.
