### ISSUE TITLE
Big Files: Redis Server went away

### ISSUE THREAD

**Issue by setiseta** [Wonderfall/dockerfiles#157]
Hello,

I'm trying to sync a file of about 300MB.
The upload in the windows client stops after a few MB with the following message:
 16.03.2017 21:28:46,                            Documents/Fotos.zip,       D:\Users\Seti\nextcloud,Blacklisting fortsetzen: Error downloading https://nextcloud.7.setadesign.net/remote.php/webdav/Documents/Fotos.zip-chunking-3036160568-30-0 - server replied: Internal Server Error (Redis server went away)

The environment for the size is set to:
UPLOAD_MAX_SIZE=10G

Any hints on how to solve it, or what i've done?
Or is there a setting wrong?

On the same host, the upload to an owncloud container works.

Kind regards,
Sebastian

**Comment by Wonderfall** [comment]
Related to https://github.com/Wonderfall/dockerfiles/issues/128#issuecomment-281509540 ?

**Comment by setiseta** [comment]
nice, this have done the trick to me.
thank you for fast reply.
