### ISSUE TITLE
[boring-nginx] Initialisation SSL échoué

### ISSUE THREAD

**Issue by Moimemeici** [Wonderfall/dockerfiles#166]
Bonjour,
Je ne sais pas si vraiment tu peux y faire quelques chose, 
Mais depuis la MAJ sur Android Nougat (7.x).
J'ai une erreur avec les app suivante: Davdroid / Nextcloud  ou Owncloud / DSub.
L'erreur est concerne l'initialisation SSL.

**Comment by Wonderfall** [comment]
Android 7.x, mais Android 7.0 ou 7.1 ? Le problème est connu avec 7.0

**Comment by Moimemeici** [comment]
Problème résolue, je pensais l'avoir signalé venant d'un problème du à android 7.x
