### ISSUE TITLE
[Nextcloud]Configurable default root

### ISSUE THREAD

**Issue by Martinius** [Wonderfall/dockerfiles#169]
There should be a path variable to change the default root of nextcloud. It is very hard to configure nginx to access a server that runs on root using a different location.It would be easy if you could tell nginx to run on /nextcloud/ instead of /. Thx keep up the good work.

**Comment by zerpex** [comment]
+1

**Comment by bhcopeland** [comment]
+1

**Comment by Wonderfall** [comment]
At the moment this can be changed in your config.php file.
I may took a look at this when `setup.sh` will be refactored.
