### ISSUE TITLE
Can't set data folder permissions

### ISSUE THREAD

**Issue by AlexeyTipunin** [Wonderfall/dockerfiles#170]
I try to run container on windows server and shared data folder to container from windows. When i run container it's work, but a can't use it, because I can't set data folder permissions.
![image](https://cloud.githubusercontent.com/assets/4958794/25063809/81e42e6a-21f6-11e7-9445-818c0ade46fe.png).

run script 
`docker run -d --name nextcloud  `
       --link db_nextcloud:db_nextcloud  `
       -v \d\dockerData\nextCloud\data:/data  `
       -v \d\dockerData\nextCloud\config:/config  `
       -v \d\dockerData\nextCloud\apps:/apps2  `
       -v \d\dockerData\nextCloud\themes:/nextcloud/themes  `
       -e UID=1000 -e GID=1000  `
       -e UPLOAD_MAX_SIZE=10G  `
       -e APC_SHM_SIZE=128M  `
       -e OPCACHE_MEM_SIZE=128  `
       -e CRON_PERIOD=15m  `
       -e TZ=Etc/UTC  `
       -e ADMIN_USER=mrrobot  `
       -e ADMIN_PASSWORD=supercomplicatedpassword  `
       -e DOMAIN=cloud.example.com  `
       -e DB_TYPE=mysql  `
       -e DB_NAME=nextcloud  `
       -e DB_USER=nextcloud  `
       -e DB_PASSWORD=supersecretpassword  `
       -e DB_HOST=db_nextcloud  `
       wonderfall/nextcloud:10.0`

Is possible to resolve it?

**Comment by AgeraluonDocker** [comment]
In case your issue is still current, this has to do with limited flexibility in file permissions when mounting from a windows host. 
I've uploaded an image that pulls from wonderfall and bypasses this check for windows hosts under ageraluon/nextcloud: https://hub.docker.com/r/ageraluon/nextcloud.
