### ISSUE TITLE
Uncaught Exception: Could not gather sufficient random data

### ISSUE THREAD

**Issue by apeyroux** [Wonderfall/dockerfiles#176]
With latest wonderfall/nextcloud image :

```
nextcloud_1     |   thrown in /nextcloud/lib/private/Security/SecureRandom.php on line 81
nextcloud_1     | PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /nextcloud/lib/private/Security/SecureRandom.php:81
nextcloud_1     | Stack trace:
nextcloud_1     | #0 /nextcloud/lib/private/Security/SecureRandom.php(81): random_int(0, 63)
nextcloud_1     | #1 /nextcloud/lib/private/AppFramework/Http/Request.php(576): OC\Security\SecureRandom->generate(20)
nextcloud_1     | #2 /nextcloud/lib/private/Log/File.php(93): OC\AppFramework\Http\Request->getId()
nextcloud_1     | #3 [internal function]: OC\Log\File::write('PHP', 'Uncaught Except...', 3)
nextcloud_1     | #4 /nextcloud/lib/private/Log.php(301): call_user_func(Array, 'PHP', 'Uncaught Except...', 3)
nextcloud_1     | #5 /nextcloud/lib/private/Log.php(159): OC\Log->log(3, 'Uncaught Except...', Array)
nextcloud_1     | #6 /nextcloud/lib/private/Log/ErrorHandler.php(68): OC\Log->critical('Uncaught Except...', Array)
nextcloud_1     | #7 [internal function]: OC\Log\ErrorHandler::onShutdown()
nextcloud_1     | #8 {main}
nextcloud_1     |   thrown in /nextcloud/lib/private/Security/SecureRandom.php on line 81
```

this looks like https://github.com/docker-library/php/issues/376

**Comment by Wonderfall** [comment]
I know, and I'm making a new image based on nginx-php : https://github.com/Wonderfall/dockerfiles/tree/master/nginx-php
It works, but I still have a few bugs to fix, then I'll push.

**Comment by apeyroux** [comment]
thanks

**Comment by Dryusdan** [comment]
Same problem with Privatebin image : https://github.com/Wonderfall/dockerfiles/tree/master/privatebin
When you send a paste, Privatebin display an error : "Impossible de créer le paste : Could not gather sufficient random data"   

Maybe PHP 7.1?
Edit 2 : I haven't time for test, but, I had got this problem with php 7.1 also... And, I correct with this extension : mbstring ... It's just a suggestion :)

**Comment by jmertin** [comment]
Have upgraded 2 systems top 11.0.3.
So far - the system running docker under debian 8.7 jessie and which had a nextcloud 11.0.2 previously on it upgraded fine.
The system running docker under RedHat 7.3 with nextcloud 11.0.1 shows that issue too.

Just for informational purposes.

**Comment by Wonderfall** [comment]
Unfortunately I have some issues with my image nginx-php. Not to mention I'll have to maintain another image. This is such an obscure issue.

@Dryusdan : `mbstring` is already included : https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/11.0/Dockerfile#L41

**Comment by Wonderfall** [comment]
Nevermind, I fixed the image, I'll push a test tag for Nextcloud very soon.

**Comment by Wonderfall** [comment]
Nevermind. Can you please update your image ? I pushed the new version based on my own nginx-php image.

**Comment by janpavlis** [comment]
I had the same problem, pulling new images solved it :-)
Thank you, appreciate your effort.

**Comment by Wonderfall** [comment]
I guess I can close this issue, feel free to reopen.
