### ISSUE TITLE
Restarting nextcloud container lets the configuration page show up again

### ISSUE THREAD

**Issue by SnowMB** [Wonderfall/dockerfiles#18]
Hello,

I'm using the nextcloud container image. Everytime I make changes to the config.php i have to restart the container. With every restart the configuration page keeps popping up. Since I already configured a database connection and admin user this makes no sense. Is there a workaround to prevent this behaviour?

**Comment by Wonderfall** [comment]
I noticed the same thing, I'm investigating.

Apparently something changed because this was the last workaround to prevent this : 
https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/9.0/run.sh#L8
And it worked... I'll see what I can do.

**Comment by SnowMB** [comment]
Hey, I found a work-around.
Manually setting `'installed' => 'true'` in the config.php on the host will prevent the config page from showing up again. Seems there is some bug while creating the config file in the first place.

**Comment by Wonderfall** [comment]
I think it's solved now, let me know if something like this happens again.
