### ISSUE TITLE
Nextcloud problems

### ISSUE THREAD

**Issue by ghost** [Wonderfall/dockerfiles#180]
Hi, and thanks for your great job

I launch nextcloud docker image with boring-nginx. 
I have two little problem 
When i visit the admin panel i have 3 erros about security.

X-Frame-Options SAMEORIGIN not enable
header X-Content-Type-Options nosniff not set
header X-XSS-Protection "1; mode=block" not set

I look nextcloud.conf in boring-nginx and all 3 option are correct with your headers_params file.
I add this in nextclound.conf without success;

add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";

Another problem when i visit the log page in the admin panel, nothing happen . A circle turns. That's all.

Nothing in boring-nginx logs

thanks in advance

**Comment by macmeck** [comment]
While I was playing around with the Nextcloud 12 image, I figured out that the `X-Frame-Options` seem to be added to the header more than once. I'm using a different proxy but I see it twice.

Removing 
`add_header X-Frame-Options "SAMEORIGIN";`
from /nginx/sites-enabled/nginx.conf does the trick for me. But some more analysis might be required here.

`curl -k -v https://<your-ip-here>` provides some insights.

**Comment by Wonderfall** [comment]
Remove `include /etc/nginx/conf/header_params` from the nextcloud server block.

@macmeck Yes it seems Nextcloud 12 is already sending X-Frame-Options.

**Comment by ghost** [comment]
It's ok without header_param.
Any idea for logging panel ?

**Comment by Wonderfall** [comment]
None at the moment
You can manually read `nextcloud.log` if needed.

**Comment by robclay** [comment]
What container / file do you:
Remove include /etc/nginx/conf/header_params from the nextcloud server block.

Just figured it out - it's within the boring-nginx config file that gets created. :)

**Comment by ghost** [comment]
@robclay  yes you can comment this lines in conf file created with boring-nginx : 
-add_header Strict-Transport-Security "max-age=xxxxx; includeSubDomains; xxxxxx";
-include /etc/nginx/conf/headers_params;
All work fine after that :)

**Comment by ghost** [comment]
@Wonderfall when I check the config.php from nextcloud, there is no log line except 'logdateformat'. After reading the doc nextcloud, I add this in my config.php file

'Log_type' => 'owncloud',
'Logfile' => 'nextcloud.log',
'Loglevel' => '2',
'Logdateformat' => 'F d, Y H: i: s',

It seems that it works

thank you for everything

**Comment by sNiXx** [comment]
Like ghost, I am currently receiving the warnings regarding security. However, looking at /nginx/sites-enabled/nginx.conf within the container, I was not able to find the line mentioned
`include /etc/nginx/conf/headers_params;`
Also, commenting out the following lines did not help either:
```
add_header X-Content-Type-Options "nosniff";
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";
```
I'm reverse proxying and these lines are also in the system's conf file and they should stay there IMO. Interestingly, only removing the lines in my system's conf file removed the security warning.

EDIT (09/06/2018): If anyone comes across this post, I would suggest looking at /nextcloud/lib/private/legacy/response.php, as the headers are defined there as well. In addition to commenting out the headers in nginx.conf (using #), comment out ("//" or /* */ for php) the lines at the end of the response.php and the warnings should disappear. Apparently, this is a precaution by Nextcloud, should your server not send those security headers)
