### ISSUE TITLE
Proxy ip in nextcloud.log

### ISSUE THREAD

**Issue by ghost** [Wonderfall/dockerfiles#182]
I use your nextcloud docker file and boring-nginx. If i look in boring-nginx log i see the real ip of my different client.
In nextcloud logs i see the ip of boring-nginx, not the real ip. The bruteforce protection of nextcloud is useless in this case. I can not use fail2ban to.
proxy_params is include in my conf file 
Can i change something ??

**Comment by Wonderfall** [comment]
What if you adds the following lines to `config.php` : 

    'trusted_proxies' => array('IP'),
    'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),

Change `IP` with your docker bridge IP address. You can find it with this command : 

    docker exec -ti nextcloud ip route

The correct IP should be displayed on the first line, something like : 

    default via 172.17.0.1 dev eth0

Tell me if it works. I might update the documentation in the future.

**Comment by ghost** [comment]
- docker exec -ti nextcloud ip route give me : 

default via 172.17.0.1 dev eth0.

If i add this in config.php : 

'trusted_proxies' => array('172.17.0.1'),
'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),

The problem is the same, but if i add the boring-nginx ip , the real client ip are shown.

When the container is restarted or recreated, its IP address change.

Is there a way to assign an IP address to the container without creating a custom network?

**Comment by Wonderfall** [comment]
Yes sorry, I'm using nginx on my host so yes, if you use boring-nginx, it's more easy : you can add a link to your nextcloud container, so you just have to add : array('boring-nginx').

**Comment by ghost** [comment]
I need to add boring-nginx in nextcloud /etc/hosts with links for this (docker started with icc=false)

But when i add "links" in nextcloud to boring-nginx i had this error:

ERROR: Circular dependency between nginx and nextcloud

**Comment by ghost** [comment]
We need to create a custom network for this. Config.php need ip adress . With the name it does not work.
With fixed ipv4 for boring-nginx all work fine.
Thanks for help ;)
