### ISSUE TITLE
[rtorrent] Run script starts executables with flipped uid/gid

### ISSUE THREAD

**Issue by duckfullstop** [Wonderfall/dockerfiles#185]
I've been trying to figure out why my rtorrent-flood container complains endlessly about permissions, and I think I've figured out a simple typo that might be heavily contributing to it. Take a look at [line 23 of run.sh](https://github.com/Wonderfall/dockerfiles/blob/master/rtorrent-flood/run.sh#L23):

```exec su-exec $GID:$UID /bin/s6-svscan /etc/s6.d```

Shouldn't this be `$UID:$GID`, as per the chown command on line 16?

**Comment by Wonderfall** [comment]
Yep, didn't pay attention.
