### ISSUE TITLE
[nextcloud] 11.0.3 carddav not working with macOS contacts.app

### ISSUE THREAD

**Issue by bleed2002** [Wonderfall/dockerfiles#187]
Not sure if this is a issue in the wonderfall stack.
I'm not able to get carddav working with macOS contacts app. Read pretty much every related 
thread/issues and tried a lot of different configuration methods, but with no luck.

Tried the following URLs:
https://MYDOMAIN/remote.php/dav/addressbooks/users/patrick/contacts/
https://MYDOMAIN/remote.php/dav/addressbooks/users/patrick/
https://MYDOMAIN/remote.php/.well-known/carddav
https://MYDOMAIN/remote.php/remote.php/dav
https://MYDOMAIN

Nextcloud version 11.0.3, macOS sierra 10.12.4, contacts app 10.0.

nextcloud.log has errors like this:
`{"reqId":"589E81N6xuB1b\/8FQIgW","remoteAddr":"xxxxx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 The REQUEST_URI (\\\/remote.php\\\/dav\\\/principals\\\/users\\\/\\\/remote.php\\\/dav\\\/principals\\\/groups\\\/) did not end with the contents of PATH_INFO (ATH_INFO). This server might be misconfigured.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(349): Sabre\\\\DAV\\\\Server->guessBaseUri()\\n#1 \\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->getBaseUri()\\n#2 \\\/nextcloud\\\/remote.php(70): Sabre\\\\DAV\\\\Server->exec()\\n#3 \\\/nextcloud\\\/remote.php(168): handleException(Object(Exception))\\n#4 {main}\",\"File\":\"\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":387,\"User\":false}","level":4,"time":"2017-05-12 11:53:34","method":"REPORT","url":"\/remote.php\/dav\/principals\/users\/\/remote.php\/dav\/principals\/groups\/","user":"--","version":"11.0.3.2"}`

So from the logs, seems that the user gets not passed correctly somehow.
Other clients work fine (tested iOS, busyContacts macOS).

Any help highly appreciated, thanks.

**Comment by hoellen** [comment]
If you still have this problem: 
I think it is related to the bruteforce protection app. 
see: https://help.nextcloud.com/t/solved-no-more-able-to-connect-via-caldav/9459
You can fix it with deleting the records in the database:
`DELETE FROM oc_bruteforce_attempts;`
