### ISSUE TITLE
Nextcloud url shortening

### ISSUE THREAD

**Issue by strothj** [Wonderfall/dockerfiles#19]
Hello,

What would be the best way to shorten the URL for Nextcloud?
I want to remove index.php from the url. They provide a video here:
https://www.youtube.com/watch?v=yqr22XG8P4w

I'm wondering if there is something that can be easily done from the container side of things or if I should perform url rewriting on the web proxy.

Thanks

**Comment by slamanna212** [comment]
There is a shortener plugin in the Apps list, go to tools, and for me , it was at the bottom. It lets you use goo.gl or your own domain

**Comment by DennyDai** [comment]
@slamanna212 Is there any plugin to remove index.php from url?

**Comment by zargony** [comment]
URLs without "index.php" would be nice indeed. 👍

**Comment by Wonderfall** [comment]
I'd like to do this, I've tried a few things, but nothing worked... This video shows how to do that but with Apache, I'm using nginx.
If someone has an idea, it is very welcome!

**Comment by cjoy** [comment]
Has anybody figured out how to remove index.php from the url?

**Comment by slamanna212** [comment]
No but I would really love to know if it's possible

**Comment by Wonderfall** [comment]
Hum... index.php was removed from the url since https://github.com/Wonderfall/dockerfiles/commit/e0c144d7cbdcef0d9b5efcf781bbef424de84090.
No ?

**Comment by slamanna212** [comment]
I just pulled files for this container last week and it's still there
somehow

**Comment by cjoy** [comment]
I didn't pull the latest image, my bad. Thanks @Wonderfall
