### ISSUE TITLE
[ rtorrent ] large .torrent files issue

### ISSUE THREAD

**Issue by zerpex** [Wonderfall/dockerfiles#191]
Hi,

I have an issue while uploading large .torrent files (2-3 Mo) : the loading seems to loop and never ends.
Tryed on two completly differents serveurs and facing the same issue on both.

Same files are well loaded when put directly on the .watch folder.

Any idea ?

z.

**Comment by Wonderfall** [comment]
I think I fixed the issue with this line : https://github.com/Wonderfall/dockerfiles/blob/master/rtorrent-flood/rtorrent.rc#L20
