### ISSUE TITLE
[ boring-nginx ] Downloads fail because of insufficient permissions for /tmp/proxy/

### ISSUE THREAD

**Issue by lengers** [Wonderfall/dockerfiles#196]
Downloads fail, according to my logfiles (`/var/log/nginx/error.log`) because of insufficient permissions for files and subdirectories in `/tmp/proxy`. 

Running `chmod -R 777 /tmp/proxy` fixes the problem until the container restarts.

**Comment by Wonderfall** [comment]
Issues like this have been noticed with old versions of aufs. I can't do anything else.
