### ISSUE TITLE
APCu Support => Disabled

### ISSUE THREAD

**Issue by baj702** [Wonderfall/dockerfiles#197]
I'm getting a lot of: "Memcache\\APCu not available for distributed cache " in nextcloud logs. According to the apcu.ini it should be enabled:

extension=apcu.so
apc.enabled=1
apc.shm_size=128M
apc.ttl=7200

But if do:
sudo docker exec -ti nextcloud php -i 

I get:
APCu Support => Disabled
Version => 5.1.8
APCu Debugging => Disabled

A relevant thread: 
https://help.nextcloud.com/t/caching-has-potentially-stopped-working-since-9-0-52-10-0-0-0-upgrade/2826

**Comment by Wykks** [comment]
`apc.enable_cli=1` is missing in the `apcu.ini`
