### ISSUE TITLE
[ rtorrent-flood ] Downloads weird file when accessing web UI

### ISSUE THREAD

**Issue by rm127** [Wonderfall/dockerfiles#198]
Each time I try to access the flood web UI on [IP]:49184 my browser starts downloading a file which is roughly half a Kb in size. In it is a lot of weird characters.

I'm unsure if I have set it up correctly, so here is my docker-compose.yml file:

    version: '2'
    
    services:
        flood:
            container_name: rTorrent-flood

            image: wonderfall/rtorrent-flood

            environment:
                FLOOD_SECRET: the storm

            tty: true

            ports:
            - "49184:49184"
            - "3000:3000"

            volumes:
            - /root/flood/downloads:/data
            - /root/flood/db:/flood-db

            networks:
            - "torrent"

    networks:
        torrent:
            driver: bridge

**Comment by Wonderfall** [comment]
49184 is not the WebUI port. 3000 is.
