### ISSUE TITLE
Synology DSM 6 with subsonic via docker

### ISSUE THREAD

**Issue by jflocke** [Wonderfall/dockerfiles#2]
HI there, 
first of all, thank you so much for your great work with the dockerfiles. 

i just installed subsonic via docker. i configurated it as far as i could. 

I can find the subsonic Server on my sonos System and can also scan the files. but when i try to Play a file, i get the error:connnection with the subsonic Server not possible.. 

can you help me out here? 

thank you so much!

**Comment by Wonderfall** [comment]
Cheerio!
Foremost it would be nice to provide me with your subsonic.log (last entries when you get this error). Secondly, it is possible that your problem is software-related, you should thus go to the Subsonic official forum since I'm not a developer. :)
