### ISSUE TITLE
Error, cron job not executed

### ISSUE THREAD

**Issue by AgeraluonDocker** [Wonderfall/dockerfiles#205]
when running this container, the system cron job does not seem to be executed at all. The terminal shows the following error message:

"Console has to be executed with the same user as the web server is operated

current user:

Web server user: root"

My image is executed with UID/GID 1000:1000 when being run via environment variables.

**Comment by Wonderfall** [comment]
Unfortunately I cannot reproduce... Cron should be executed with the same UID/GID as the web server since we run everything from s6 with su-exec.

**Comment by AgeraluonDocker** [comment]
would it be possible to run cron explicitly with the same UID/GID as specified in the enviconment variables? Or is that already being done?

**Comment by Wonderfall** [comment]
This is already being done : https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/rootfs/usr/local/bin/run.sh#L38

Re-open if needed.
