### ISSUE TITLE
[nextcloud] How to bind port to nginx?

### ISSUE THREAD

**Issue by rol1** [Wonderfall/dockerfiles#206]
Hi,

i'm trying to setup the nextcloud (and mariadb) latest on my samll home server. This server has nginx already running. I thougt i could "reach" nextcloud via 127.0.0.1:8888, which did not work. I can reach it via 172.17.0.3:8888. What do i have to do to reach it from my local net?
I read the "Reverse proxy" chapter of the documentation, where you metion two possibilities: nginx on the host itselv, or in an extra docker container. But i don't know what do do here, if this is the solution.

Thank you very much

Roland

**Comment by Wonderfall** [comment]
Documentation updated.

> What do i have to do to reach it from my local net?

Otherwise this can be solved by using docker-compose.yml to configure your nextcloud container: 

```
ports:
  - 127.0.0.1:8888:8888
```
