### ISSUE TITLE
Question: Nextcloud version 12.0 beta 1

### ISSUE THREAD

**Issue by mikedolx** [Wonderfall/dockerfiles#208]
Hi,

I was wondering why i can't download the latest Nextcloud version 12.0.0.0. Instead everytime i run the command

`docker run -d --name nextcloud [.. options ..] wonderfall/nextcloud:12.0`

I get the 12.0 beta 1 Version. Afaik the stable version of NC12 is already released.

Has the image been updated with the latest NC version?

Thanks and Regards

**Comment by Wonderfall** [comment]
Did you pull the latest one?

**Comment by mikedolx** [comment]
I pulled the image with the "latest" tag right now and it's the stable released version 12.0.0.0. That's ok for me, but i was expecting to get the stable 12.0 when using the tag 12.0. 
A confusion from my side - sorry.

**Comment by Wonderfall** [comment]
I can assure you that you can get the 12.0 stable from the tag 12.0.
https://hub.docker.com/r/wonderfall/nextcloud/builds/bxduejhqjgc9tn9sqg22fbf/

You may need to pull again this tag.
