### ISSUE TITLE
rtorrent -> tracker could not resolve hostname.

### ISSUE THREAD

**Issue by changemenemo** [Wonderfall/dockerfiles#209]
hi,
My 80+ torrents can't contact trackers . 
Did you compile the rtorrent with libcurl like suggested here : [603 issue of rtorrent](https://github.com/rakshasa/rtorrent/issues/603)  ?

check also the version of curl : [535 issue of rtorrent](https://github.com/rakshasa/rtorrent/issues/535)

**Comment by changemenemo** [comment]
still no idea for this problem?

**Comment by changemenemo** [comment]
seems a bit less problematic than before, don't know if you have done nay changes or if it's the sublayer container bases that have changed the result by being updated.

**Comment by Wonderfall** [comment]
I couldn't reproduce. It seems you may have issues with Docker DNS settings?
The container should just work fine and the version of libcurl should be okay. If you notice the 100% CPU bug, it's not due to libcurl itself : https://github.com/Wonderfall/dockerfiles/tree/master/rtorrent-flood#note
