### ISSUE TITLE
Nextcloud: "Please use https" error when using https

### ISSUE THREAD

**Issue by bluepuma77** [Wonderfall/dockerfiles#21]
When running `wonderfall/nextcloud` with [nginx-proxy](https://github.com/jwilder/nginx-proxy) `jwilder/nginx-proxy` and [nginx-letsencrypt](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) `jrcs/letsencrypt-nginx-proxy-companion` I get an error 'Please use https'. With other services I can use external https and internal http without a problem. Somehow Nextcloud does not recognize the https connection in front of the proxy. Any ideas how to get this working?

```
sudo docker run -d \
  --name db_nextcloud \
  -v /mnt/nextcloud/db:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD=supersecretpassword \
  -e MYSQL_DATABASE=nextcloud \
  -e MYSQL_USER=nextcloud \
  -e MYSQL_PASSWORD=supersecretpassword \
  mariadb:10

sudo docker run -d \
  --name nextcloud \
  -e VIRTUAL_HOST=my.domain \
  -e LETSENCRYPT_HOST=my.domain \
  -e LETSENCRYPT_EMAIL=my@email \
  --link db_nextcloud:db_nextcloud \
  -e UID=1000 -e GID=1000 \
  -v /mnt/nextcloud/data:/data \
  -v /mnt/nextcloud/config:/config \
  -v /mnt/nextcloud/apps:/apps2 \
  wonderfall/nextcloud
```

**Comment by Wonderfall** [comment]
Are these proxy settings set on nginx proxy side?

```
proxy_set_header        Host                 $host;
proxy_set_header        X-Real-IP            $remote_addr;
proxy_set_header        X-Forwarded-For      $proxy_add_x_forwarded_for;
proxy_set_header        X-Remote-Port        $remote_port;
proxy_set_header        X-Forwarded-Proto    $scheme;
proxy_redirect          off;
```

**Comment by cjoy** [comment]
I have added the following to my proxy settings, but it's still not working. 
I get this error:
ERR_CONNECTION_REFUSED
