### ISSUE TITLE
Communication de Flood-rtorrent avec Transdroid ?

### ISSUE THREAD

**Issue by angarod** [Wonderfall/dockerfiles#210]
Je ne sais pas s'il y a un support pour transdroid, mais flood, que j'utilise depuis plusieurs mois, ne semble pas le supporter. 
Il y a peut être quelque chose à faire de ce coté la.

**Comment by angarod** [comment]
Une erreur de ma part dans la conf du reverse proxy. Ca fonctionne.

**Comment by remihb** [comment]
Salut, as-tu un exemple de config dans transdroid.
Pour ma part je n'arrive pas à faire communiquer les deux, pourtant tout le reste fonctionne.

**Comment by angarod** [comment]
location /scgi {
        scgi_pass 127.0.0.1:5000;
        include scgi_params;
    }
à rajouter dans la conf de nginx

**Comment by remihb** [comment]
Ok cool, thx.

**Comment by noraj** [comment]
@angarod https://rawsec.ml/en/archlinux-install-rtorrent-flood-sftp/
