### ISSUE TITLE
[Nextcloud] App Updates are not persistent

### ISSUE THREAD

**Issue by matthiasbaldi** [Wonderfall/dockerfiles#212]
Hi
Almost everthing works great incl. Redis cache etc. Thanks for that great images!
But when I update apps wich I have activated manually (i.e. Groupfolders) it would only update the app in the active container. If I do a docker-compose down and a docker-compose up -d (cold start) then the app updates are lost and I have to update the stuff again.

Is that a bug or a bad configuration on my system or just wanted?
How can I prevent this phenomen?
Thanks.

**Comment by hoellen** [comment]
In my Nextcloud configuration the writeable Apps folder is e.g. "/apps2"

config.php (excerpt)
```
'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
```

So you have to add /apps2 to your volumes in docker. So the folder is persistent:

docker-compose.yml (excerpt)
```
volumes:                                     
    - /etc/localtime:/etc/localtime:ro         
    - ./data:/data                             
    - ./config:/config                         
    - ./apps:/apps2 
```

Hope that helps you for your Nextcloud instance. 
greets

**Comment by matthiasbaldi** [comment]
@hoellen Oh thank you.
I had the mounting into the container but I didn't set the config.php configuration.
Thanks a lot.
