### ISSUE TITLE
[nextcloud] run.sh not coping config.php back to /config when container is stopped/removed

### ISSUE THREAD

**Issue by watermelonpizza** [Wonderfall/dockerfiles#22]
When you stop the container, all the database, admin and data location information in config.php is lost. 
By stopping or halting/deleting the container you lose the config.php file, thus having to redo the initial setup installation in nextcloud.

Mounting /config to a volume isn't good enough because the 'live' config.php file isn't copied back from /nextcloud/config/config.php :stuck_out_tongue: 

Maybe a symbolic/hard link to the /config folder would be better?

**Comment by Wonderfall** [comment]
The 'live' config.php is copied when the container start. But you shouldn't have an existing /config/config.php before the setup installation, this can lead to the problem you described.

Anyway I'm planning to change this to something better.

**Comment by watermelonpizza** [comment]
Ah ok, I must have set it up incorrectly then. 

> Anyway I'm planning to change this to something better.

Cool :) Managed to get it working now anyway, so if you are changing it no need to worry about this problem.
