### ISSUE TITLE
[nextcloud] No starts after first run!

### ISSUE THREAD

**Issue by devedetti** [Wonderfall/dockerfiles#225]
Hi, I tested this image running `docker run -d -p 8080:8888 --name nextcloud wonderfall/nextcloud:latest`

All works ok!

```
/ # ps
PID   USER     TIME   COMMAND
    1 991        0:00 /bin/s6-svscan /etc/s6.d
   71 991        0:00 s6-supervise nginx
   72 991        0:00 s6-supervise php
   73 991        0:00 s6-supervise cron
   74 991        0:00 {run} /bin/sh ./run
   75 991        0:00 nginx: master process nginx
   76 991        0:00 php-fpm: master process (/php/etc/php-fpm.conf)
   78 991        0:00 nginx: worker process
   79 991        0:00 nginx: worker process
   80 991        0:00 nginx: worker process
   81 991        0:00 nginx: worker process
  210 991        0:00 php-fpm: pool www
  211 991        0:00 php-fpm: pool www
  212 991        0:00 sleep 15m
  222 root       0:00 /bin/sh
  228 root       0:00 ps
```

Then I dropped the container to create a more specific configuration but does not starts internally

```
/ # ps 
PID   USER     TIME   COMMAND
    1 root       0:00 {run.sh} /bin/sh /usr/local/bin/run.sh
   14 root       0:00 chown -R 991:991 /nextcloud
   15 root       0:00 /bin/sh
   20 root       0:00 ps
```

It no more works! I tested this procedure in two computers with the same results!
I can't rebuild the container and get it working :'(

**Comment by devedetti** [comment]
I don't know why at the first run the chown went fast!
In the new builds it is too slow and this is why the container appears to fail!

Anyone knows how to solve this problem?

```
 TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
 5589 be/4 root        0.00 B/s   86.62 K/s  0.00 %  0.00 % chown -R 991:991 /nextcloud
```

**Comment by Wonderfall** [comment]
Are you using overlay2 as the storage driver?

**Comment by devedetti** [comment]
Hi @Wonderfall  Yes, I'm using overlay2 [1]

I really appreciate any help you can provide


[1] The file writting performance (uploaded from nextcloud) reach ~150MB/s.

**Comment by Wonderfall** [comment]
Unfortunately this bug is known for a while, and I can't do anything else on my side...
I personally migrated to the btrfs storage driver, and the `chown` process takes a few seconds, even less.
