### ISSUE TITLE
[flood] https support?

### ISSUE THREAD

**Issue by changemenemo** [Wonderfall/dockerfiles#228]
Will you add https support? Because you reverse proxy is on 3000, I'm okey with that but so it goes to 80 no ?

**Comment by Wonderfall** [comment]
There's no need to add HTTPS support to these images as long as you set up correctly your reverse proxy. You shouldn't just bind the port 3000 of the container to the port 80 of the host, what you should do is making the reverse proxy communicate with the proxied container at port 3000, and expose the reverse proxy with HTTPS if you want. You can use nginx to do that : https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass

**Comment by changemenemo** [comment]
So I need 2 containers then? I didn't bind the 3000 to 80 but to o whole different port to have external connectivity . so more something like -p 49000:3000 and so I was hoping that your container were embedding everything we need. But so if I understand you correctly I need to put  another container in front  of it bind to the 3000 port of your container and bind another port for external connectivity . right?

**Comment by Wonderfall** [comment]
Perhaps this can explain better what I meant : https://github.com/Wonderfall/dockerfiles/tree/master/nextcloud#reverse-proxy
