### ISSUE TITLE
Add php7-sqlite3

### ISSUE THREAD

**Issue by tifredfr** [Wonderfall/dockerfiles#23]
Hi,

Request to add php7-sqlite3. Ideal for quickly testing nextcloud (demo, dev ...)

Thx

**Comment by Wonderfall** [comment]
Hi,
Support for sqlite was supposed to be added (for the same reasons I thought it'd be better) in the latest image. It was successful when I tried it with the 10.0 version, perhaps I missed something when I commited. I'll look at it when I have time, are you sure the option for sqlite database is not present?

**Comment by tifredfr** [comment]
I tested daily, without SQLite support, it may lack php7-sqlite3 in your dockerfile ?

**Comment by Wonderfall** [comment]
I was almost sure it worked with `php7-pdo_sqlite` instead of `php7-sqlite3`.
That's why I pushed https://github.com/Wonderfall/dockerfiles/commit/3aaed43c5fa8368cb3df2d688fc2f367c3de228d.

Apparently not, thanks for reporting.

**Comment by tifredfr** [comment]
You're welcome ;)

**Comment by Wonderfall** [comment]
https://github.com/Wonderfall/dockerfiles/commit/14cddd6caa24634b5cac32059b199c008643398d
