### ISSUE TITLE
Configuration Issue - Webgui not accessible

### ISSUE THREAD

**Issue by aspeitkamp** [Wonderfall/dockerfiles#232]
Hi all,
most likely a configuration issue on my end, but I cannot seem to be able to work it out myself.
This is what I did:

1) Start DB:

```
docker run -d --name db_nextcloud \
        -v /home/docker/nextcloud_docker/db:/var/lib/mysql \
        -e MYSQL_ROOT_PASSWORD=REDACTED \
        -e MYSQL_DATABASE=nextcloud -e MYSQL_USER=nextcloud \
        -e MYSQL_PASSWORD=REDACTED \
        mariadb:latest
```

This runs without any obvious errors. 

2) Start Nexcloud

```
docker run -d --name nextcloud \
       --link db_nextcloud:db_nextcloud \
       -v /mnt/pool/nextcloud/data:/data \
       -v /home/docker/nextcloud_docker/config:/config \
       -v /home/docker/nextcloud_docker/apps:/apps2 \
       -v /home/docker/nextcloud_docker/themes:/nextcloud/themes \
       -e UID=1000 -e GID=1000 \
       -e UPLOAD_MAX_SIZE=10G \
       -e APC_SHM_SIZE=128M \
       -e OPCACHE_MEM_SIZE=128 \
       -e CRON_PERIOD=15m \
       -e TZ=Etc/UTC \
       -e DOMAIN=localhost \
       -e DB_TYPE=mysql \
       -e DB_NAME=nextcloud \
       -e DB_USER=nextcloud \
       -e DB_PASSWORD=REDACTED \
       -e DB_HOST=db_nextcloud \
       wonderfall/nextcloud:latest
```

Also no obvious (for me at least) errors. Unfortunately I cannot access the webgui from inside the local LAN (from a different PC). Other docker containers e.g. plex, unifi seem to be working fine and are accessible.

3) Logs
Not sure if I got everything but this is what I did:
`docker logs -f nextcloud`
which gives

> Updating permissions...
> Updating permissions in /nextcloud...
> Permissions in /data are correct.
> Permissions in /config are correct.
> Permissions in /apps2 are correct.
> Updating permissions in /var/log...
> Updating permissions in /php...
> Updating permissions in /nginx...
> Updating permissions in /tmp...
> Updating permissions in /etc/s6.d...
> Done updating permissions.
> Nextcloud is already latest version

`docker stats nextcloud`

> CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
> nextcloud           0.00%               54.23MiB / 15.63GiB   0.34%               206kB / 76.7kB      446kB / 170MB       142

`docker ps`
> CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS               NAMES
> bfe491794b23        wonderfall/nextcloud:latest   "run.sh"                 About an hour ago   Up About an hour    8888/tcp            nextcloud
> 2f30e7a6e276        mariadb:latest                "docker-entrypoint..."   About an hour ago   Up About an hour    3306/tcp            db_nextcloud

To be complete a `addr ip` gives:
```
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 34:64:a9:9a:9b:18 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.6/24 brd 192.168.1.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet6 fe80::642e:31cf:715f:33b7/64 scope link 
       valid_lft forever preferred_lft forever
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 34:64:a9:9a:9b:19 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.7/24 brd 192.168.1.255 scope global eno2
       valid_lft forever preferred_lft forever
    inet6 fe80::c6a0:d622:f85a:b974/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:dc:78:8b:ae brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::1836:95a6:f723:2858/64 scope link 
       valid_lft forever preferred_lft forever
```
I used the following URL to try to access the webgui:

- `192.168.1.6:8888`
- `nas:8888`
- `http://192.168.1.6:8888`
- `https://192.168.1.6:8888`

I would be very glad if somebody could push me into the right direction with this. I guess it must be somthing obious for the docker experienced users...

Thanks!

**Comment by aspeitkamp** [comment]
Ok, I am an idiot... changing to port 5001 worked. 

So something must have been using 8888. I did check this previously with `netstat`, but I must have messed up, since I didn't see that it must have been used...

So problem seems to be solved for me. Thanks

**Comment by robclay** [comment]
How did you "change" to port 5001?

**Comment by aspeitkamp** [comment]
Simply by starting the container with the port parameter:
`docker run -d -p 5001:8888 --name nextcloud \` 
followed by the rest of the parameters...
