### ISSUE TITLE
nextcloud 10 smb missing

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [Wonderfall/dockerfiles#27]
Hi there,

i recently moved my installation from owncloud to nextcloud 10 using the wonderfall/nextcloud:10.0 image. Now i have the problem that my previously used external storage pathes with smb are not usable. It seemed, that smb is not installed or recognized correctly, because it does not show up in the external storage type list.

**Comment by Wonderfall** [comment]
Did it work before? Can you get some log entries? Thanks!

**Comment by cguentherTUChemnitz** [comment]
## How i upgraded:

I upgraded directly from from the owncloud docker image l3iggs/owncloud:9.0.1-1. Therefore i remapped the volumes and modified the data directory in the config.php. Afterwards i was able to run the serverside updater which had no problems. I was forced to use the server side one, because of a large installation.

## Current Situation:

Everything runs fine, except the external storage smb support. The external storage was already used before the upgrade. So the entries exist already, but are not usable. When looking at the admin panel, the external storage type SMB does not exist anymore. Errorlog entries are generated, when i try to access the broken external storage:

> Exception: {"Exception":"OCP\Files\StorageNotAvailableException","Message":"Unknown error (sh: stdbuf: not found)","Code":0,"Trace":"#0 \/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php(171): OCA\Files_External\Lib\Storage\SMB->getFileInfo('\/')\n#1 \/nextcloud\/lib\/private\/Files\/Storage\/Common.php(437): OCA\Files_External\Lib\Storage\SMB->stat('')\n#2 \/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php(438): OC\Files\Storage\Common->test()\n#3 \/nextcloud\/apps\/files_external\/lib\/config.php(233): OCA\Files_External\Lib\Storage\SMB->test(false, false)\n#4 \/nextcloud\/apps\/files_external\/lib\/Controller\/StoragesController.php(255): OC_Mount_Config::getBackendStatus('\\OCA\\Files_Exte...', Array, false, false)\n#5 \/nextcloud\/apps\/files_external\/lib\/Controller\/UserGlobalStoragesController.php(121): OCA\Files_External\Controller\StoragesController->updateStorageStatus(Object(OCA\Files_External\Lib\StorageConfig), false)\n#6 [internal function]: OCA\Files_External\Controller\UserGlobalStoragesController->show(2, false)\n#7 \/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#8 \/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_External\Controller\UserGlobalStoragesController), 'show')\n#9 \/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_External\Controller\UserGlobalStoragesController), 'show')\n#10 \/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Files_Exter...', 'show', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#11 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)\n#12 \/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)\n#13 \/nextcloud\/lib\/base.php(967): OC\Route\Router->match('\/apps\/files_ext...')\n#14 \/nextcloud\/index.php(48): OC::handleRequest()\n#15 {main}","File":"\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php","Line":133}

**Comment by cguentherTUChemnitz** [comment]
Are you able to select the smb storage type in the admin panel using the wonderfall/nextcloud:10.0  image? Is it reproducible that this storage type is not listed?

**Comment by jrtolle** [comment]
Yes, this is reproducible.  Even with the old latest (v9 something), SMB connectivity did not work out-of-the-box.  If I log into the image and `apk add samba-client`, it works fine.  Otherwise, I get the SMB will not work error when I go into external storage settings.  I use SMB users, as well, and they obviously do not work.  The error in the log is that smbclient is missing.  It appears libsmbclient-php is not available on Alpine Linux, so I had to install the samba-client package when testing.

Reference #29 for fix.

**Comment by Wonderfall** [comment]
Thanks!
