### ISSUE TITLE
How to execute "occ upgrade"?

### ISSUE THREAD

**Issue by nrgeen** [Wonderfall/dockerfiles#28]
Hello,

at the moment for me it isn't possible to upgrade to NC10. :-(
I suspect my database or complete installation is to big (and the execution time to short?).

Therefore I want to use "occ upgrade".
Under Debian the handling ist familar for me, among alpine linux it is not.
It would be great to get an hint or some help, how to execute it.
Thanks a lot in advance!

**Comment by Wonderfall** [comment]
```
docker exec -ti nextcloud sh
su nextcloud
cd nextcloud
php7 occ upgrade
exit
```

Did you get any message when you tried to update the first time?

**Comment by nrgeen** [comment]
There was no particular error. It was something like "An error occurred", nothing more.
Your tip worked very well, so I could perform the update now without any problems.
Many thanks!

**Comment by nrgeen** [comment]
Thanks for the new "occ" solution! (commit: nextcloud: add occ shortcut) 
It works well and is also easy to reach.
