### ISSUE TITLE
Rainloop : [105] Missing version directory error

### ISSUE THREAD

**Issue by hardware** [Wonderfall/dockerfiles#3]
Salut Wonderfall,

j'ai un petit soucis avec rainloop, après avoir créé le conteneur, je rencontre cette erreur en ouvrant rainloop depuis un navigateur :

`[105] Missing version directory`

https://github.com/RainLoop/rainloop-webmail/blob/master/index.php#L10

Pourtant j'ai bien ce répertoire dans le conteneur oO :

```
docker exec -ti rainloop sh
ls -al /rainloop/rainloop/v/1.9.4.415

total 36
drw-rw-rw-    8 rainloop rainloop      4096 May  5 08:56 .
drw-rw-rw-    4 rainloop rainloop      4096 May  5 08:56 ..
drw-rw-rw-   12 rainloop rainloop      4096 May  5 08:56 app
-rw-r--r--    1 rainloop rainloop      1135 May  5 08:56 check.php
-rw-r--r--    1 rainloop rainloop      8148 May  5 08:56 include.php
-rw-r--r--    1 rainloop rainloop         0 May  5 08:56 index.php
-rw-r--r--    1 rainloop rainloop       447 May  5 08:56 index.php.root
drw-rw-rw-   12 rainloop rainloop      4096 May  5 08:56 static
drw-rw-rw-   28 rainloop rainloop      4096 May  5 08:56 themes
```

J'ai du oublier un truc, ça doit être tout con mais je vois pas :smile:

**Comment by Wonderfall** [comment]
J'ai remarqué la même chose, et je pense que tu n'as rien dû oublier.
`/rainloop/rainloop/v/VERSION/include.php` existe bel et bien...

Ça peut paraître débile mais peut-être qu'il faut essayer de déplacer `/rainloop` ailleurs, dans `/var/www` par exemple. En même temps je vois pas d'autre moyen, avant ça marchait parfaitement...

**Comment by hardware** [comment]
Solution :

```
find /rainloop -type d -exec chmod 755 {} \;
find /rainloop -type f -exec chmod 644 {} \;
```

Peut-être à cause d'une modification des permissions par défaut dans l'archive `rainloop-community-latest.zip`, en tout cas le site officiel recommande de faire comme ça pour attribuer les bons droits aux fichiers et répertoires. 

Affaire classée :smile:
