### ISSUE TITLE
Nexcloud : missing php cli ?

### ISSUE THREAD

**Issue by zerpex** [Wonderfall/dockerfiles#32]
Hi there,

While looking to use occ commands (specificaly to force a full scan), I was unable to find php cli : 

```
# docker exec -it nextcloud sh
/ # cd /nextcloud/
/nextcloud # su - nextcloud
06fc87f8772b:~$ /nextcloud/occ files:scan --all
env: can't execute 'php': No such file or directory
```

```
06fc87f8772b~$ php -v
sh: php: not found
```

(no more success in root)

Is there an other way to do it ?
I no, can you include php cli on the container ?

Note : by default /nexcloud/oss is not executable.

Regards,
zer.

**Comment by zerpex** [comment]
Nevermind, github noob user there, didn't saw the "closed" section.

using php7 instead of php is working: 

`06fc87f8772b:~$ php7 /nextcloud/occ files:scan --all`

Thanks

**Comment by Wonderfall** [comment]
No problem, and there's an occ shortcut now. :)
https://github.com/Wonderfall/dockerfiles/commit/a5061c81b1c271af04861c9b199f05882eb195b5
