### ISSUE TITLE
Nextcloud iconv issue

### ISSUE THREAD

**Issue by moonwolf-github** [Wonderfall/dockerfiles#33]
Do you plan address this: https://github.com/docker-library/php/issues/240?

It may be solution for my problem with LDAP user mapping...

**Comment by Wonderfall** [comment]
I also ran into some problems, for instance with the Mail app due to this iconv issue.
If I understand well, I should build the `iconv` extension myself using the GNU libiconv.

**Comment by Wonderfall** [comment]
I did it. :)
Will push soon. That fixes issues with the Mail app by the way.

**Comment by Wonderfall** [comment]
https://github.com/Wonderfall/dockerfiles/commit/c68dafa3916816e38c6fe19bee67ad9d1c0a5b85
