### ISSUE TITLE
Nextcloud permission issue

### ISSUE THREAD

**Issue by cwildfoerster** [Wonderfall/dockerfiles#34]
Hi, after the upgrade i receive the following nginx error:

`nginx: [emerg] mkdir() "/var/lib/nginx/tmp/proxy" failed (13: Permission denied)`

it seems like the chown in run.sh is wrong but it seems okay because its -R...

**Comment by Daniel133** [comment]
+1

**Comment by Wonderfall** [comment]
It's a known problem and yet I've seen no fix, it happens randomly. The only workaround is to move /var/lib/nginx/tmp/proxy to /tmp/proxy, I'll do that a bit later.

**Comment by Daniel133** [comment]
After the update: nginx: [emerg] mkdir() "/var/lib/nginx/tmp/uwsgi" failed (13: Permission denied)

**Comment by Wonderfall** [comment]
Now ?

**Comment by Daniel133** [comment]
nginx: [emerg] mkdir() "/var/lib/nginx/tmp/scgi" failed (13: Permission denied)

After I created the folder "scgi" manually it works! Please add the folder also to /tmp.

**Comment by Wonderfall** [comment]
You can also add `scgi_temp_path /tmp/uwsgi 1 2;` to `/etc/nginx/nginx.conf`.
So no more errors after scgi ?

**Comment by Daniel133** [comment]
Right, after scgi nginx starts.
