### ISSUE TITLE
Fix rainloop nginx permissions

### ISSUE THREAD

**Issue by jcnoir** [Wonderfall/dockerfiles#36]
I think that the rainloop image needs the same patch than nexcloud for nginx permissions in non root mode (/etc/nginx.conf):

```
proxy_temp_path /tmp/proxy 1 2;
uwsgi_temp_path /tmp/uwsgi 1 2;
scgi_temp_path /tmp/scgi 1 2;
```

Thanks for these great images !

**Comment by Wonderfall** [comment]
https://github.com/Wonderfall/dockerfiles/commit/9c8f89a41e99289ca181c2e236f4532ee6b49195

**Comment by jcnoir** [comment]
Thank you for the quick fix !
