### ISSUE TITLE
Owncloud / Contact App

### ISSUE THREAD

**Issue by Moimemeici** [Wonderfall/dockerfiles#4]
Bonjour,
après plusieurs test je me rends compte qu'il y a un problème avec l'application Contact.
Je m'explique.
si on prend Thunderbird avec Cardav ou tout autre d'ailleurs et que l'on crée un contact avec plusieurs informations. A priori çà fonctionne sans aucun soucis.
Si on prend un contact et qu' on incorpore un Avatar, Contact App tourne en boucle.
état initial:
![initial](https://cloud.githubusercontent.com/assets/19207283/15044744/e77deb60-12d6-11e6-82cf-bf13dad9bd64.PNG)
Avec un avatar:
![avec avatar](https://cloud.githubusercontent.com/assets/19207283/15044778/0ea51740-12d7-11e6-9de2-13e19489bd07.PNG)
Sans Avatar
![sans avatar](https://cloud.githubusercontent.com/assets/19207283/15044772/082a344a-12d7-11e6-87bf-99986ac476d1.PNG)
A priori j'ai lu quelques part qu'il y aurait un problème avec PHP7 (mais je ne trouve plus le lien)
Voici d'autre chose lien que j'ai trouvé.
https://github.com/owncloud/contacts/pull/380
https://github.com/owncloud/contacts/pull/392
https://github.com/owncloud/core/issues/22978

**Comment by Moimemeici** [comment]
Après plusieurs, test, il s'avère que ce n'est pas l'ajout d'avatar qui pose problème.
Une fois qu'il y a un peu de fiche contact, le problème revient et empêche l'app contact de fonctionner.
Je ne sais pas ou trouver les logs, j'ai vérifier pas mal de log sans qu'il y est de problème apparent.

**Comment by Wonderfall** [comment]
Je ne suis pas parvenu à reproduire le problème, à partir de combien de fiches le problème apparaît selon toi ?

**Comment by Moimemeici** [comment]
Tout dépends mais souvent au dessus de 45/50 mais les fiches doivent être remplie correctement
Nom/prénom/Adresse/Tel Fixe/Tel Portable

**Comment by Moimemeici** [comment]
La version 9.0.2 ne régle pas le problème, a priori il y a quand même évolution les clients carddav arrive a se connecter quand même et a récupérer les fiches

**Comment by Wonderfall** [comment]
T'es sûr que `owncloud.log` n'indique rien de croustillant ? 
Ou `/var/log/nginx/error.log` dans le conteneur owncloud.

**Comment by Moimemeici** [comment]
Voilà ce que j'ai avec la version 8.2 de owncloud, je réinstalle la 9.0.2 d'ici tout à l'heure

```
2016/05/06 18:08:02 [crit] 49#49: *1 connect() to unix:/run/php/php7.0-fpm.sock failed (13: 
Permission denied) while connecting to upstream, client: 172.17.0.8, server: , request: "GET /index.php/apps/contacts/ HTTP/1.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "mondomaine.cloud"

```

**Comment by Moimemeici** [comment]
Voila ce que j'ai en reinstallant la version 9.0.2
C'est peut être un début non ?

```
# tail -f /var/log/php7/error.log
[07-May-2016 10:48:02] NOTICE: fpm is running, pid 18
[07-May-2016 10:48:02] NOTICE: ready to handle connections
[07-May-2016 10:59:30] NOTICE: fpm is running, pid 17
[07-May-2016 10:59:30] NOTICE: ready to handle connections
[07-May-2016 11:00:45] NOTICE: fpm is running, pid 26
[07-May-2016 11:00:45] NOTICE: ready to handle connections
[07-May-2016 11:04:03] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
```

**Comment by Moimemeici** [comment]
En appliquant ce correctif dans /etc/php7/php-fpm.d/www.conf
J'arrive enfin a pouvoir récuperer sur le contenue via thunderbird et une extension du type cardbook

```
 pm = dynamic
 pm.max_children = 4
 pm.start_servers = 1
 pm.min_spare_servers = 1
 pm.max_spare_servers = 2
 pm.max_requests = 500
```

Plus d'erreur maintenant du type 
`[07-May-2016 11:04:03] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it`

Par contre sur owncloud les contacts reste inaccessible.

**Comment by Moimemeici** [comment]
Salut, juste un message concernant davdroid ! 
https://github.com/square/okhttp/issues/2506

**Comment by Wonderfall** [comment]
Encore des problèmes ?

**Comment by Wonderfall** [comment]
Le problème provient bien d'HTTP/2 et d'OKHTTP.
Les clients qui utilisent OKHTTP commencent à réagir en bloquant directement HTTP/2, sinon il fallait désactiver le protocole côté serveur. Pas encore de support en vue, qui va sûrement nécessiter une mise à jour du code chez OKHTTP et chez nginx...

**Comment by Wonderfall** [comment]
Résolu : https://github.com/Wonderfall/dockerfiles/commit/a0c54ec1cf85b5de62c4b7d5f19fdb553eacad02
