### ISSUE TITLE
persistent root /apps folder

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [Wonderfall/dockerfiles#43]
Hi there, i am trying to get spreed.me working in conjunction with this nextcloud image. Regarding to this [discussion](https://github.com/strukturag/nextcloud-spreedme/issues/22) it is possible to check some essential setup stuff, by appanding the following stuff to the nextcloud url:

> /index.php/apps/spreedme/admin/debug

This was the point, where i determined some trouble with the current nextcloud image. The second test 

> testOwncloudJavascriptConfigFile

fails with:

> Did not find OwnCloudConfig.js at apps/spreedme/extra/static/config/OwnCloudConfig.js.

Looking at the [code](https://github.com/strukturag/nextcloud-spreedme/blob/d547c94a961949be5f4a69461216227d7994c560/debug/debug.php) shows that they do some static lookup into the root /apps folder.

Now here come the problem with the nextcloud image. I am not able to serve my apps in a persistent way in the root /apps folder. When following your guidelines they are placed in the root /apps2 folder. However i managed to get it temporarily working when symlinking the /nextcloud/apps to /apps and not using the "apps_paths" nextcloud config. But this is not convinient either, because it is not persistent and i need the app content inside a mounted volume.

Is it possible with your nextcloud image to server the apps in the root /apps folder in a mounted volume? More generally spoken, did anyone managed to get the [spreed.me ](https://hub.docker.com/r/spreed/webrtc/) docker image running in conjunction with this nextcloud image?

**Comment by cguentherTUChemnitz** [comment]
I found myself a more then less hacky solution. Using the /nextcloud/apps folder as a docker volume breaks the container, because the folder is empty after container startup, but the nextcloud instance assumes the defualt apps there.

Using different pathes for persistent apps as proposed by wonderfall in the [readme](https://hub.docker.com/r/wonderfall/nextcloud/) is not a suitable solution, because the spreedme app assumes to live in the default app path/url.

My dirty hack is currently to clone the plugin from [github](https://github.com/strukturag/nextcloud-spreedme) and mount that folder as a nextcloud volume into /nextcloud/apps/spreedme. In this way i am able to share the necessary config between the nextcloud and the spreedme container.

Nevertheless, i would see this as an dirty hack for the current situation. Either the **spreedme plugin** should learn to handle **alternative app pathes,** and / or the **wonderfall nextcloud** image should also present a possibility to **mount the default app path** as a docker volume.

best,
Christian

PS:
this fixes the spreedme app configuration test using the url ending `index.php/apps/spreedme/admin/debug`

> Spreed.ME Version 0.3.2
> 
> Ran test #1 (testOwncloudPhpConfigFile):
>    Passed without an error
> 
> Ran test #2 (testOwncloudJavascriptConfigFile):
>    Passed without an error
> 
> Ran test #3 (testSpreedWebRTCAPI):
>    Passed without an error
> 
> Passed all tests. Everything seems to be set up correctly! :)

Nevertheless the service is not functional yet. It seems that i run into some kind of the [no one else here](https://github.com/strukturag/nextcloud-spreedme/issues/35) bug. I think i will paste some logs in their project bug tracker.

**Comment by ghost** [comment]
ich verstehe dich nicht. bei mir läuft es :)
https://github.com/strukturag/spreed-webrtc/issues/369

**Comment by cguentherTUChemnitz** [comment]
Thanks for the clarification that is runs fine in your setup. I got my setup running and removed also my dirty hack. It seems that the spreedme tests are not aware of handling alternative plugin pathes. Running the spreedme plugin in the apps2 folder the second test fails with:

> Ran test #2 (testOwncloudJavascriptConfigFile):
>    Error: Did not find OwnCloudConfig.js at apps/spreedme/extra/static/config/OwnCloudConfig.js

Nevertheless the app itself seems to run fine. So i will present the problem to the spreedme team.
