### ISSUE TITLE
[Nextcloud] Error after upgrading to 10.0.1: unexpected newline

### ISSUE THREAD

**Issue by jdoubleu** [Wonderfall/dockerfiles#47]
I'm getting

```
Fatal Error Zend OPcache cannot allocate buffer for interned strings
./run: line 5: syntax error: unexpected newline
```

from the `Wonderfall/nextcloud` container after startup.

I've tried tag `10.0` and `latest` and an image pulled 44 hours ago.

I'm using an image from 13 days ago now and it works again.

**Comment by Wonderfall** [comment]
I've just upgraded flawlessly, I couldn't reproduce it. If you didn't try the following trick, could you run manually `run.sh` in a container so you can maybe get more details from `/var/log/php7/error.log` ?

**Comment by jdoubleu** [comment]
Yeah seems to be a problem on my host. I pulled it locally and it works there.

I'm going to investigate it.

---

Seemed to be caused by a custom `php-fpm` config??
Not using this any more so everything works, thanks!
