### ISSUE TITLE
supported Hardware [RasPi]

### ISSUE THREAD

**Issue by tulamidan** [Wonderfall/dockerfiles#49]
Heya
I was just double checking if this image will run on a Raspi or similar ARM based system #

**Comment by Wonderfall** [comment]
No, this image will only run on x86_64 system.
However I think ARM support can easily be done, I just have to find an Alpine ARM image.

**Comment by tulamidan** [comment]
This would be a sweet addition. I believe the other nextcloud images (indiehosters, greyltc..) won't run on a raspi either, right?
Alpine offers a RPI tarball on the official download page: [http://dl-cdn.alpinelinux.org/alpine/v3.4/releases/armhf/alpine-rpi-3.4.4-armhf.rpi.tar.gz](url)
And a docker image with a minimal installation of Alpine from hypriot: [https://github.com/hypriot/rpi-alpine-scratch](url)

**Comment by Wonderfall** [comment]
Yes and I've found some on Docker Hub. I'll see what I can do this weekend but as I don't have much time for this, it'd be great if you could check if any package is not supported by Alpine for ARM platforms : https://pkgs.alpinelinux.org/packages, though it looks good to me!

armhf (Pi 2/3) : https://hub.docker.com/r/armhf/alpine/
aarch64 (Pine64) : https://hub.docker.com/r/owlab/alpine-arm64/

**Comment by tulamidan** [comment]
I've hat some time to fiddle with your Dockerfile and built an ARM ready Image. Haven't tested yet, but before you spend the same time I'd like to send you the file. It's still quick & dirty. So I'll just send it to the address mentioned as "Maintainer"

**Comment by Wonderfall** [comment]
Got it working by using `orax/alpine-armhf:edge`. However this will needs documentation.

EDIT : And I can't make an automated build for it... This is annoying.

**Comment by tulamidan** [comment]
I remember reading sth. about automated build issues for the Raspi builds. Maybe this still isn't fixed.
Did you have a look at the Dockerfile I've sent you? Works with the armhf/alpine linux. Only passing the environment variable for the Opcache value does not.
64 is a good value for the Raspi A - 128 will break the image.

**Comment by Wonderfall** [comment]
Yes I know but `armhf/alpine` does not maintain the `edge` tag actually, I don't know why, but it has to be built regularly for security reasons. That's why I think `orax/alpine-armhf:edge` is better for now.

I know the issue about memory & caching, this was exactly the reason I had in mind when I added these environment variables.

**Comment by grenzr** [comment]
Great work on the ARM version btw.. I had trouble getting native samba-client working with SMB shares, however I have managed to `pecl install smbclient` after wading through a bunch of Alpine dependencies first. I'll PR you this soon, as it works nicely.

**Comment by SplicedNZ** [comment]
Hi there, just wanted to note that `docker build -t wonderfall/nextcloud .` fails with `standard_init_linux.go:175: exec user process caused "exec format error"
`
On Archlinux aarch64 running on the rpi3

**Comment by Wonderfall** [comment]
It doesn't support yet aarch64. If you could make a PR that would be welcome!
