### ISSUE TITLE
Owncloud / Problème Intégrité Fichier

### ISSUE THREAD

**Issue by Moimemeici** [Wonderfall/dockerfiles#5]
Depuis ta dernière modification, il y a une erreur d'intégrité fichiers:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
    - INVALID_HASH
        - lib/private/appframework/http/request.php

Raw output
========== 
```

**Comment by Wonderfall** [comment]
Comme cette issue l'explique : https://github.com/owncloud/core/pull/24343
... il fallait modifier request.php car la mise à jour vers PHP 7.0.6 (une mise à jour de sécurité, avant on était à la 7.0.5), sans rentrer dans les détails, a "cassé" des choses dont par exemple la possibilité même de se connecter. Donc j'ai ajouté le fix en urgence.

Tu peux donc interpréter ce résultat comme un faux positif.
D'ailleurs où as-tu vu cette erreur ?

**Comment by Moimemeici** [comment]
Je l'ai vu dans le panneau d'administration.

**Comment by Wonderfall** [comment]
Résolu avec https://github.com/Wonderfall/dockerfiles/commit/1e5c70712eee98faa69bebe08c7ba25fe3cbb404 (passage à 9.0.2).
