### ISSUE TITLE
Support for docker-entrypoint.d (at least in NextCloud)

### ISSUE THREAD

**Issue by cjeanneret** [Wonderfall/dockerfiles#51]
Hello,

I'd like to be able to extend your image in a convenient way, calling the "occ" command line so that I can pre-configure nextcloud in an automated way.
I'm pretty sure I'm not the only one seeking that kind of feature - care to have a look?

Thank you!

Cheers,

C.

**Comment by jdoubleu** [comment]
Do you just want to have access to the `occ` inside the container? There's [already `occ`](https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/10.0/occ) you can access like this: `docker exec  -it my-nextcloud occ ...`.

Or do you want to be able to mount some scripts in `/docker-entrypoint.d` which will be ran on start?
If so why don't you just create your own image based on this?
And what exactly do you want to configure that you can't simply add it to the config file?

**Comment by cjeanneret** [comment]
Hello,

In fact, I've created an image based on yours — the whole point of having a "docker-entrypoint.d" directory and related support is to be able to do so without having to replace the "run.sh" script — I'll provide a pull-request this week so that you can see what can be done.

Having the support in your image directly allows people to extend it in a convenient and easy way. A bit like the "postgresql" docker image.

I have "some" configuration to push in nextcloud, using the "occ" through "su-exec" directly in the entrypoint script — that allows me to automate the instance deploy, its configuration (database, admin name) and some tuning (theming). All isn't directly in the configuration file, and thus it's easier to use a script called at startup.

Cheers,

C.

**Comment by Wonderfall** [comment]
Since your last post, autoconfiguration for database was added.
But I like the idea, PR is welcome. :)
