### ISSUE TITLE
SMTP sending fails next cloud

### ISSUE THREAD

**Issue by grimkroton** [Wonderfall/dockerfiles#52]
Hi,

I have your lovely next cloud-container running, but I am not able to send mails with the php-mailer. I tried 2 different hoster (start and gmail). But with both hosters, I wasn't able to receive mails. The nextcloud logs told me, that the mail was sent.

Regards

**Comment by DarianAnjuhal** [comment]
I have the same problem. php mail not working and my hoster (netcup) neither.
I am not sure how to detect the issue. In the container mail is not installed. So I guess its normal that php mail is not working.

Thx and bye
Darian

**Comment by Wonderfall** [comment]
It worked for me when I was using my own mailserver. I'll try soon with Gmail/Gandi.

**Comment by grimkroton** [comment]
I got this workaround: Get the container IP and open firewall with the source IP from container. Then I reconfigured postfix to listen on the docker0 interface. In Nextcloud you have to use the gateway IP to your dockerhost.

So I am relaying from my Nextcloud container via the postfix on the dockerhost to the target.

Regards
