### ISSUE TITLE
Nginx: compiling issue

### ISSUE THREAD

**Issue by bdestombe** [Wonderfall/dockerfiles#55]
Hi,
First of all, thanks for your docker files, I am a big fan.

When I just tried to compile nginx, it showed some problems. These problems seem to be related to:
https://github.com/google/ngx_brotli/issues/39

The following temporary workaround is suggested by PiotrSikora,

> For the time being, you can work around this issue by adding -Wno-deprecated-declarations to the --with-cc-opt=.

This seems to work for me

**Comment by Wonderfall** [comment]
Should be okay now (#57)
