### ISSUE TITLE
Nginx: suggestion to include map module

### ISSUE THREAD

**Issue by bdestombe** [Wonderfall/dockerfiles#56]
Jupyter notebook is a web environment for various programming languages. It has quite a big user base and is quickly growing. To get secure connections, your nginx proxy container is great. It works almost out of the box, only the map_module needs to be included. 

I was wondering whether you could consider including the map module in the nginx compiling options.

Actually omitting the following line:

```
--without-http_map_module \
```

Thanks!

**Comment by Wonderfall** [comment]
Hey, I'm sorry but if I start to do that, I will have to add a module every time someone requests me. I'd like to keep this image as lean as possible. Feel free to fork and make an image which will suit your needs!

**Comment by bdestombe** [comment]
I understand, thanks though!
