### ISSUE TITLE
nginx proxy for a directory

### ISSUE THREAD

**Issue by patgg** [Wonderfall/dockerfiles#58]
Hello,
something failed when i try to configure the proxy for postfixadmin and rainloop.
i can just see postfixadmin. i can't connect to rainloop.
i tryied to modify the nginx proxy for that postfixadmin be in a specific directory /pf/ :
Webroot (default is /): /pf/
it indicates that :
WARNING: You might have to add a proxy header to get your custom webroot working.
it request this :
Type the required proxy_set_header (like X-Script-Name):
i know apache2 config, but not really nginx, what would be the good line ?

nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in /sites-enabled/postfixadmin.conf:25

location /pf/ {
proxy_pass http://postfixadmin:8888;
proxy_set_header Host $host/pf/;
include /etc/nginx/conf/proxy_params;
}

Is there a little tuto to do that ? manuals are good, but i don't understand what to do.
thx

**Comment by abc34** [comment]
File proxy_params already contains proxy_set_header Host $host.
