### ISSUE TITLE
Tini has been relocated to /sbin/tini

### ISSUE THREAD

**Issue by hardware** [Wonderfall/dockerfiles#6]
Salut,

Je viens de mettre à jour mon reverse et maintenant j'obtiens ce warning dans les logs docker :

```
docker logs nginx

WARNING: Tini has been relocated to /sbin/tini.
Please update your scripts to use /sbin/tini going forward.
/usr/bin/tini has been preserved for backwards compatibility in Alpine 3.4,
but WILL BE REMOVED in Alpine 3.5.
```

ça doit concerner tes autres images aussi, voila :)

**Comment by Wonderfall** [comment]
Oui apparemment tini est passé en 9.0.0-**r1**.
Cependant je ne vois pas trop ce que je dois modifier...

**Comment by hardware** [comment]
Ouais y a peut-être rien à modifier en fait, juste vérifier que **/sbin** est bien dans $PATH (normalement oui), comme ça la commande **tini** pointera bien sur **/sbin/tini** et plus **/usr/bin/tini** lors du passage à Alpine 3.5

**Comment by Wonderfall** [comment]
Oui **/sbin** est bien dans $PATH...
Je pense que c'est juste un warning à titre indicatif, bizarre.

**Comment by Wonderfall** [comment]
Cf. https://github.com/krallin/tini/issues/38.
Pour se débarrasser du warning, il faut utiliser `/sbin/tini`, parce qu'avec `tini` on utilise le symlink `/usr/bin/tini` à l'origine du warning. Une solution serait de préciser `/sbin/tini`.

**Comment by Wonderfall** [comment]
Done.
