### ISSUE TITLE
Beta versions of Piwik

### ISSUE THREAD

**Issue by jdoubleu** [Wonderfall/dockerfiles#60]
Will there be container tags for the beta releases of Piwik?
So I can test the new versions.

https://piwik.org/changelog/

**Comment by Wonderfall** [comment]
I'm sorry but I actually don't have enough time to maintain beta releases, I hope you will understand. As you certainly know you can build yourself with `VERSION=3.0.0-beta2` for instance, or you can fork if you want Docker Hub builds.
