### ISSUE TITLE
Symfony exception

### ISSUE THREAD

**Issue by hruoho** [Wonderfall/dockerfiles#63]
The provided docker-compose.yaml (v2) for wonderfall/nextcloud results to the following output no matter which version/label I try:
```
Nextcloud is not installed - only a limited number of commands are available
                                                                 
 [Symfony\Component\Console\Exception\CommandNotFoundException]  
 Command "upgrade" is not defined.                               
                                                                
Trying ownCloud upgrade again to work around ownCloud upgrade bug...
Nextcloud is not installed - only a limited number of commands are available
                                                                 
 [Symfony\Component\Console\Exception\CommandNotFoundException]  
 Command "upgrade" is not defined. 
```

Any hints?

**Comment by jrpbuilds** [comment]
Having the exact same issue running on CentOS 7.2

Docker version 1.12.3, build 6b644ec

**Comment by jrpbuilds** [comment]
Solution: Remove your config directory and re-pull/launch the instance. Fixed it for me

**Comment by malteneuss** [comment]
I had the same issue, but resolved it by giving the mariadb container more time on the first startup (30 seconds on my machine) to finish its initialization before starting the nextcloud container.

**Comment by Wonderfall** [comment]
As stated by the README you should wait at least 15 seconds for mariadb to come up. Although I'm using docker-compose V1 format and I didn't encounter this issue.

I'll try myself with docker-compose V2 file ASAP.
