### ISSUE TITLE
Nextcloud : sqlite is broken

### ISSUE THREAD

**Issue by openhs** [Wonderfall/dockerfiles#64]
I got error when running a container from nextcloud:10.0 image:

> docker run -it --rm --name nextcloud wonderfall/nextcloud:10.0
> Starting automatic configuration...
> creating sqlite db
> Automatic configuration finished.
> An exception occurred while executing 'UPDATE "oc_appconfig" SET "configvalue" = ? WHERE ("appid" = ?) AND ("configkey" = ?) AND ("configvalue" <> ?)' with params ["no", "firstrunwizard", "enabled", "no"]:
> 
> SQLSTATE[HY000]: General error: 8 attempt to write a readonly database
> [06-Nov-2016 13:23:02] NOTICE: fpm is running, pid 84
> [06-Nov-2016 13:23:02] NOTICE: ready to handle connections
> {"reqId":"V4G7G4NcB1MiLsG1oeLF","remoteAddr":"","app":"cron","message":"An exception occurred while executing 'DELETE FROM \"oc_appconfig\" WHERE (\"appid\" = ?) AND (\"configkey\" = ?)' with params [\"core\", \"cronErrors\"]:\n\nSQLSTATE[HY000]: General error: 8 attempt to write a readonly database","level":4,"time":"2016-11-06 13:23:02","method":"--","url":"--","user":"--"}

I've tried to set DB_NAME, DB_USER and DB_PASSWORD but the result was the same.

Accessing the instance from the browser shows an error that the domain is untrusted. After I add it as trusted it shows Internal Server Error upon login (no additional error is in the log).

**Comment by Wonderfall** [comment]
DB_NAME DB_USER DB_PASSWORD are only useful for configuring other databases than sqlite. You're actually using sqlite and I've seen these errors before but you can forget them.

Modify `trusted_domains` in your config.php, this should do the trick.
Example : 

```
  'trusted_domains' =>
  array (
    0 => 'yournextcloud.com',
  ),
```

**Comment by openhs** [comment]
I'm already using different image but if you still interested, the bug was **not caused** by DB_NAME, DB_USER and DB_PASSWORD variables.  I've tried to set them **after** I saw the error "attempt to write a readonly database" (with no effect).

Also, the trusted domain I was able to add successfully.  The problem is what happened after that; which is: **Internal Server Error**.

In short, the problem here is:

`SQLSTATE[HY000]: General error: 8 attempt to write a readonly database`

after "clean install".  Just download image and run a container.

**Comment by Wonderfall** [comment]
Like I said, I had the same error but it didn't cause the Internal Server Error issue.
How did you add the trusted domain? If you did this through the web interface, it may not work.

I will try a clean install.

**Comment by Wonderfall** [comment]
Ok I do now understand your issue. It seems sqlite is broken and I don't know why because it worked before. Since sqlite is not recommended by Nextcloud I think I will remove definitely its support, but perhaps we can fix it.

**Comment by Wonderfall** [comment]
It was just a permission error caused by a PR merged one day before your post.
Chown /data in setup.sh should fix the problem.

**Comment by Poikilos** [comment]
> It was just a permission error caused by a PR merged one day before your post.
> Chown /data in setup.sh should fix the problem.

Resolved with the following chown line (I had to use the old version since my migration path was ownCloud 10.0.10 to Nextcloud 12.0.12, then the upgrade path was to Nextcloud 13.0.10; cd to owncloud or Nextcloud directory first): `sudo chown -R www-data:www-data data`
I also did `sudo service apache2 restart` but I'm not sure whether that was needed.

In my case, I had already cleared the cache manually (data/appdata_*/css/ and data/appdata_*/js) as per <https://github.com/nextcloud/server/issues/8043#issuecomment-360776226>, so I also did `sudo -u www-data ./occ files:scan-app-data`.
