### ISSUE TITLE
strange nginx error

### ISSUE THREAD

**Issue by evilp** [Wonderfall/dockerfiles#68]
Hi,
when i start the armhf container then a nginx error occurs:
2016/11/13 15:05:14 [emerg] 3069#3069: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)

the strange thing is that in /etc/nginx/nginx.conf the error log should be /tmp/ngx_error.log:
error_log /tmp/ngx_error.log error; 

any suggestion?

**Comment by Wonderfall** [comment]
Duplicate : https://github.com/Wonderfall/dockerfiles/issues/37
I know it's annoying, but you'll have to find a way to update aufs (update to 4.x or later).
