### ISSUE TITLE
cannot implement ownpad

### ISSUE THREAD

**Issue by abidueiro** [Wonderfall/dockerfiles#74]
Hi,

I tried many things to make ownpad working, we already have an etehrpad working in our server and we would love to connect to our Nextcloud container. I did everithing on here: https://github.com/otetard/ownpad/blob/master/README.md

except `sudo -u www-data php occ files:scan --all` because I do it like on docker like:

`docker exec -ti container_name www-data php occ files:scan --all`

but get this error:

rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"www-data\\\": executable file not found in $PATH\"\n"

Could you give me some help?

Thanks

**Comment by Wonderfall** [comment]
This command won't work. Instead you can do something even more simple : 
`docker exec -ti container_name occ files:scan --all`

The container has indeed an occ shortcut : https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/11.0/occ

**Comment by abidueiro** [comment]
Hi Wonderfall, 

Thanks for your answer, now just remember that used command as you suggest and now again. Command gave no errors, then I restart Nextcloud docker-compose, but still couldn't edit thoose paths within Nextcloud. 

Any suggestions, please?

**Comment by Wonderfall** [comment]
I don't use Ownpad so I can't really help. At least you can provide some logs?

**Comment by abidueiro** [comment]
Hi Wonderfall, I realized that even volume `"./.nextcloud/config:/config"` is mapped on my docker-compose.yml there are not the same files there. In nextcloud folder on server side I have mimetypemapping.json but not on Docker side. But I put the file there by docker `exec -it container_id /bin/sh` and is remaining there even if I restart the containers. Then I can say problem solved. Thanks!

**Comment by cdauth** [comment]
I would like this issue to be reopened. To configure ownPad, it is necessary to create file `mimetypemappings.json` in the config folder. In previous versions of this Docker image it was possible to simply mount this file into `/nextcloud/config/mimetypemappings.json`, but in the newer versions this does not work, as the mysterious `mv nextcloud fix && mv fix nextcloud # fix strange bug` line will fail and break the nextcloud installation.

The best way to do it if `run.sh` would link `mimetypemappings.json` from `/config` in the same way as it does `config.php`.
