### ISSUE TITLE
New Nextcloud container takes ages to change permissions

### ISSUE THREAD

**Issue by ConorIA** [Wonderfall/dockerfiles#75]
I am not sure if this is something new, or if I only noticed it now when I tried to upgrade my nextcloud instance to 11.0. The default UID and GID are both 991, however, when the container starts, all of the files in the nextcloud folder belong to nobody:nogroup. I wasn't sure why nothing was coming up on my container, so I tried to run the run.sh script manually. It froze at the do loop that chowns all the files to $UID:$GID. I changed the flags on that command to include -v, and sure enough, almost all of the files in the container need to be chowned before the run file completes. I will leave it running and see if and when the nextcloud container actually starts, but for now there is absolutely nothing in the logs.

**Comment by Wonderfall** [comment]
Unfortunately I haven't seen this before, and I tested the latest PR which should avoid this issue. I will take a look again when I have time but I'm 95% sure there's nothing wrong with run.sh

**Comment by ConorIA** [comment]
I don't think the issue is with `run.sh`, but rather the fact, that the default installation files are owned by nobody:nogroup, instead of the default 1000:1000. Maybe even a message in the log that says 'Updating permissions' so that when a user types docker logs -f nextcloud, they at least see something is happening. 

Anyway, this is just because I was a fool and couldn't figure out why my Nextcloud service wasn't coming up. I must have run docker-compose up -d a million times before I realized that the files were being `chown`-ed.
