### ISSUE TITLE
Error building nginx with brotli

### ISSUE THREAD

**Issue by Miaourt** [Wonderfall/dockerfiles#76]
As seen on the docker ci / locally :
https://hub.docker.com/r/wonderfall/boring-nginx/builds/bwefentucfdxnpfiddjx4q5/

**Comment by Wonderfall** [comment]
Yeah related to this : https://github.com/Wonderfall/dockerfiles/pull/73#issuecomment-267810201
It's easy to fix but the major concern now is how to compile nginx 1.11.7 against BoringSSL without error.
