### ISSUE TITLE
[nextcloud] preview generation cronjob

### ISSUE THREAD

**Issue by hoellen** [Wonderfall/dockerfiles#77]
Hey, 
thanks for all your great work. 
There is a question I have for the nextcloud dockerfiles: 
I want to use the App [Preview Generator](https://apps.nextcloud.com/apps/previewgenerator) to render all the thumbnails at night (4:30 AM) 
Usually I used the following cron job:
<code>
30 4 * * * nginx php -f /var/www/html/cloud/occ preview:pre-generate
</code>

But how can I use it in the docker container? 
I tried to adopt your "[15 min cron job](https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/11.0/s6.d/cron/run)" for nextcloud with <code>sleep 86400</code> (24 h), but there is the problem that I don't know how to start at 4:30 AM. Any help?

Thanks.

**Comment by Wonderfall** [comment]
Add this command to the crontab on the host : 
`docker exec -ti nextcloud occ preview:pre-generate`

**Comment by hoellen** [comment]
Aah so easy. I didn't thought about it. Thank you!
