### ISSUE TITLE
Owncloud / Configuration non sauvegardé.

### ISSUE THREAD

**Issue by Moimemeici** [Wonderfall/dockerfiles#8]
Salut, 
quand on utilise le serveur de mail pour les notification, on le configure en smtp, après un restart du conteneur, on perd la configuration.
Cordialement

(c'est juste pour information)

**Comment by Wonderfall** [comment]
Je le sais bien, j'ai été confronté au même problème. Il suffit juste de voir le config.php qui a été sauvegardé après avoir redémarré le conteneur, il contient toutes les directives nécessaires qu'il suffit alors d'ajouter au config.php actuel (puis redémarrer encore une fois pour appliquer).

**Comment by Moimemeici** [comment]
Ah ok, je crois que chez nous on ne reçoit plus les notifications. Mais je vais vérifier
