### ISSUE TITLE
[nextcloud] cron job runs permanently

### ISSUE THREAD

**Issue by mikedolx** [Wonderfall/dockerfiles#86]
Hi,
first of all thanks for the great nexcloud docker image. 

I have a question regarding cron jobs. The nextcloud container is running on my synology nas. I monitored the cpu and volume load and realized, that the container creates a high hdd load. After a look into the logs and process overview i saw that the nextcloud's cron job is constantly running (24/7). After logging into the container with an shell, i saw that one cron is spawned after another.
How can i check the cronjob is started. I have already checked the crontab of the root user but no cronjob for the nextcloud is listed there.

I have set the environment variable CRON_PERIOD to 15m. I also tried 30m but with no success.

Do you have an idea?

Thanks

**Comment by mikedolx** [comment]
I found something. I observed a strange message in my container log, appearing constantly:

```
sleep: invalid number '15M'
sleep: invalid number '15M'
sleep: invalid number '15M'
sleep: invalid number '15M'
```
after a bit of research i found the S6 supervisor configuration file 
```/etc/s6.d/cron/run```

The original content was as follows
```
#!/bin/sh                                                                           
                                                                                    
while true; do                                                                      
  php7 -f /nextcloud/cron.php                                                       
  sleep 15m                                                               
done 
```
I removed the "m" from "sleep 15m" and rebooted my container. Now the mysterious error message is gone so far. Furthermore, my HDD load dropped to a 'normal level'.

Could it be, that you have a nasty typo in the supervisor definition?

Btw. Shouldn't the supervisor definition contain any variable which is fed by the container variable CRON_PERIOD?

Thanks and Regards,

**Comment by Wonderfall** [comment]
Very strange, I can't reproduce this. As you may know, `15M` is not a correct value but `15m` is.
By removing "m" it is the same as setting a sleep interval of 15 seconds and that's not a good idea for your disks.

What if you leave CRON_PERIOD unset (by default it'll be 15m)?

**Comment by mikedolx** [comment]
Do i have to rebuild the container, or do I just restart it, when I remove CRON_PERIOD?

I will retry it.

Thanks

**Comment by Wonderfall** [comment]
You'll have to recreate the container, usually docker-compose does this automatically if it detects a change like this

**Comment by mikedolx** [comment]
I have retried it on the weekend, and it was working fine. I guess i set the initial value of CRON_PERIOD to 15M, when i was creating the container. 

Thanks!
