### ISSUE TITLE
postgresql support

### ISSUE THREAD

**Issue by flypenguin** [Wonderfall/dockerfiles#9]
could you also include postgresql support into the image? currently you state there's only maria/mysql support.

**Comment by Wonderfall** [comment]
I suppose you mean Nextcloud.

**Comment by flypenguin** [comment]
yes I did, sorry  :) . is there a separate tracker to enter this?

**Comment by Wonderfall** [comment]
As you can see, I closed your issue after adding PostgreSQL support, it should work now. ;)

**Comment by flypenguin** [comment]
awesome :) . didn't see that you actually added postgres support, thanks!

2016-06-27 12:04 GMT+02:00 Wonderfall notifications@github.com:
